(function() {
    const searchInput = document.getElementById('search-input');
    const searchForm = document.querySelector('.search-form');
    const searchSuggestions = document.getElementById('search-suggestions');
    const searchResultsPage = document.getElementById('search-results-page');
    const resultsTitle = document.getElementById('search-results-title');
    const resultsNote = document.getElementById('search-results-note');
    const resultsGrid = document.getElementById('search-results-grid');
    const resultsClose = document.getElementById('search-results-close');

    if (!searchInput || !searchForm || !searchSuggestions || !searchResultsPage || !resultsTitle || !resultsNote || !resultsGrid || !resultsClose) {
        return;
    }

    const games = [
        { title: '2048', href: '/g/2048/' },
{ title: '10 Minutes Till Dawn', href: '/g/10-minutes-till-dawn/' },
{ title: '1010 Color Match', href: '/g/1010-color-match/' },
{ title: '12 Mini Battles 2', href: '/g/12-mini-battles-2/' },
{ title: '12 Minibattles', href: '/g/12-minibattles/' },
{ title: '18 Wheeler Cargo Simulator', href: '/g/18-wheeler-cargo-simulator/' },
{ title: '18 Wheeler Cargo Simulator 2', href: '/g/18-wheeler-cargo-simulator-2/' },
{ title: '18 Wheeler Driving Sim', href: '/g/18-wheeler-driving-sim/' },
{ title: '18 Wheeler Truck Parking', href: '/g/18-wheeler-truck-parking/' },
{ title: '18 Wheeler Truck Parking 2', href: '/g/18-wheeler-truck-parking-2/' },
{ title: '1v1 Lol', href: '/g/1v1-lol/' },
{ title: '2048 Cupcakes', href: '/g/2048-cupcakes/' },
{ title: '2048 Fusion', href: '/g/2048-fusion/' },
{ title: '3 Pandas in Japan', href: '/g/3-pandas-in-japan/' },
{ title: '3d Bowling', href: '/g/3d-bowling/' },
{ title: '3d Free Kick', href: '/g/3d-free-kick/' },
{ title: '4x4 Off Road', href: '/g/4x4-off-road/' },
{ title: '99 Balls', href: '/g/99-balls/' },
{ title: '99 Nights in the Forest', href: '/g/99-nights-in-the-forest/' },
{ title: 'a Dance of Fire and Ice', href: '/g/a-dance-of-fire-and-ice/' },
{ title: 'a Small World Cup', href: '/g/a-small-world-cup/' },
{ title: 'Achievement Unlocked', href: '/g/achievement-unlocked/' },
{ title: 'Adam and Eve 5 Part 1', href: '/g/adam-and-eve-5-part-1/' },
{ title: 'Adam and Eve 5 Part 2', href: '/g/adam-and-eve-5-part-2/' },
{ title: 'Adam and Eve 6', href: '/g/adam-and-eve-6/' },
{ title: 'Adam and Eve 7', href: '/g/adam-and-eve-7/' },
{ title: 'Adventure Drivers', href: '/g/adventure-drivers/' },
{ title: 'Agarpaper Io', href: '/g/agarpaper-io/' },
{ title: 'Alien Hominid Hd', href: '/g/alien-hominid-hd/' },
{ title: 'Amazing Strange Rope Police Vice Spider Vegas', href: '/g/amazing-strange-rope-police-vice-spider-vegas/' },
{ title: 'Amidst the Sky', href: '/g/amidst-the-sky/' },
{ title: 'Among Us', href: '/g/among-us/' },
{ title: 'Amongus Io', href: '/g/amongus-io/' },
{ title: 'Ancient Sins', href: '/g/ancient-sins/' },
{ title: 'Angry Gran Run', href: '/g/angry-gran-run/' },
{ title: 'Apple Shooter', href: '/g/apple-shooter/' },
{ title: 'Aquapark Io', href: '/g/aquapark-io/' },
{ title: 'Arcane Archer', href: '/g/arcane-archer/' },
{ title: 'Archery World Tour', href: '/g/archery-world-tour/' },
{ title: 'Arena Noob Vs Pro', href: '/g/arena-noob-vs-pro/' },
{ title: 'Arras Io', href: '/g/arras-io/' },
{ title: 'Arsonate', href: '/g/arsonate/' },
{ title: 'Aspiring Artist', href: '/g/aspiring-artist/' },
{ title: 'Awesome Tanks 2', href: '/g/awesome-tanks-2/' },
{ title: 'Backflipper', href: '/g/backflipper/' },
{ title: 'Backrooms 2d', href: '/g/backrooms-2d/' },
{ title: 'Bacon May Die', href: '/g/bacon-may-die/' },
{ title: 'Bad Egg', href: '/g/bad-egg/' },
{ title: 'Bad Ice Cream 2', href: '/g/bad-ice-cream-2/' },
{ title: 'Bad Ice Cream 3', href: '/g/bad-ice-cream-3/' },
{ title: 'Bad Monday Simulator', href: '/g/bad-monday-simulator/' },
{ title: 'Baldis Basics', href: '/g/baldis-basics/' },
{ title: 'Baldis Basics Field Trip', href: '/g/baldis-basics-field-trip/' },
{ title: 'Ball Sort Halloween', href: '/g/ball-sort-halloween/' },
{ title: 'Ball Sort Soccer', href: '/g/ball-sort-soccer/' },
{ title: 'Ballistic', href: '/g/ballistic/' },
{ title: 'Basket and Ball', href: '/g/basket-and-ball/' },
{ title: 'Basket Random', href: '/g/basket-random/' },
{ title: 'Basketball Clash', href: '/g/basketball-clash/' },
{ title: 'Basketball Dunkshot', href: '/g/basketball-dunkshot/' },
{ title: 'Basketball Legends 2020', href: '/g/basketball-legends-2020/' },
{ title: 'Basketball Skills', href: '/g/basketball-skills/' },
{ title: 'Basketball Stars', href: '/g/basketball-stars/' },
{ title: 'Basketball Stars 2019', href: '/g/basketball-stars-2019/' },
{ title: 'Basketball Superstars', href: '/g/basketball-superstars/' },
{ title: 'Basketbros', href: '/g/basketbros/' },
{ title: 'Basketbros Io', href: '/g/basketbros-io/' },
{ title: 'Batter Up', href: '/g/batter-up/' },
{ title: 'Battledudes Io', href: '/g/battledudes-io/' },
{ title: 'Betrayal Io', href: '/g/betrayal-io/' },
{ title: 'Big Tower Tiny Square', href: '/g/big-tower-tiny-square/' },
{ title: 'Bike Racing', href: '/g/bike-racing/' },
{ title: 'Bikers Street', href: '/g/bikers-street/' },
{ title: 'Billiards', href: '/g/billiards/' },
{ title: 'Bio Evil 4', href: '/g/bio-evil-4/' },
{ title: 'Bitlife', href: '/g/bitlife/' },
{ title: 'Block the Pig', href: '/g/block-the-pig/' },
{ title: 'Block World', href: '/g/block-world/' },
{ title: 'Blockpost', href: '/g/blockpost/' },
{ title: 'Blocktanks Io', href: '/g/blocktanks-io/' },
{ title: 'Blocky Snakes', href: '/g/blocky-snakes/' },
{ title: 'Bloons Td Battles 2', href: '/g/bloons-td-battles-2/' },
{ title: 'Bloons Tower Defense 4', href: '/g/bloons-tower-defense-4/' },
{ title: 'Bloxd Io', href: '/g/bloxd-io/' },
{ title: 'Bloxorz', href: '/g/bloxorz/' },
{ title: 'Blumgi Bloom', href: '/g/blumgi-bloom/' },
{ title: 'Blumgi Rocket', href: '/g/blumgi-rocket/' },
{ title: 'Blumgi Slime', href: '/g/blumgi-slime/' },
{ title: 'Bob the Robber 2', href: '/g/bob-the-robber-2/' },
{ title: 'Bobblehead Soccer Royale', href: '/g/bobblehead-soccer-royale/' },
{ title: 'Bottle Flip', href: '/g/bottle-flip/' },
{ title: 'Bottle Flip 3d', href: '/g/bottle-flip-3d/' },
{ title: 'Bouncy Woods', href: '/g/bouncy-woods/' },
{ title: 'Bowling Stars', href: '/g/bowling-stars/' },
{ title: 'Boxing Physics 2', href: '/g/boxing-physics-2/' },
{ title: 'Boxing Random', href: '/g/boxing-random/' },
{ title: 'Boxing Stars', href: '/g/boxing-stars/' },
{ title: 'Braains Io', href: '/g/braains-io/' },
{ title: 'Breaking the Bank', href: '/g/breaking-the-bank/' },
{ title: 'Bubble Pop Adventures', href: '/g/bubble-pop-adventures/' },
{ title: 'Bullet Force', href: '/g/bullet-force/' },
{ title: 'Bullet Heroes', href: '/g/bullet-heroes/' },
{ title: 'Bullet Party 2', href: '/g/bullet-party-2/' },
{ title: 'Burger Clicker', href: '/g/burger-clicker/' },
{ title: 'Burrito Bison Launcha Libre', href: '/g/burrito-bison-launcha-libre/' },
{ title: 'Candy Crush Saga', href: '/g/candy-crush-saga/' },
{ title: 'Cannon Basketball 4', href: '/g/cannon-basketball-4/' },
{ title: 'Car Rush', href: '/g/car-rush/' },
{ title: 'Car Simulator 2', href: '/g/car-simulator-2/' },
{ title: 'Carball Io', href: '/g/carball-io/' },
{ title: 'Case Clicker', href: '/g/case-clicker/' },
{ title: 'Cat Gunner Super Zombie Shoot', href: '/g/cat-gunner-super-zombie-shoot/' },
{ title: 'Cats', href: '/g/cats/' },
{ title: 'Checkers', href: '/g/checkers/' },
{ title: 'Chicken Merge', href: '/g/chicken-merge/' },
{ title: 'Choppy Orc', href: '/g/choppy-orc/' },
{ title: 'Chrome Dino', href: '/g/chrome-dino/' },
{ title: 'Circlo0', href: '/g/circlo0/' },
{ title: 'City Coach Bus Simulator 3d', href: '/g/city-coach-bus-simulator-3d/' },
{ title: 'Clicker Heroes', href: '/g/clicker-heroes/' },
{ title: 'Climbing Over It', href: '/g/climbing-over-it/' },
{ title: 'Command Strike Fps', href: '/g/command-strike-fps/' },
{ title: 'Connect 3', href: '/g/connect-3/' },
{ title: 'Cookie Clicker', href: '/g/cookie-clicker/' },
{ title: 'Craftmine', href: '/g/craftmine/' },
{ title: 'Crazy Cars', href: '/g/crazy-cars/' },
{ title: 'Crazy Tunnel 3d', href: '/g/crazy-tunnel-3d/' },
{ title: 'Creative Kill Chamber', href: '/g/creative-kill-chamber/' },
{ title: 'Cricket Hero', href: '/g/cricket-hero/' },
{ title: 'Cricket World Cup', href: '/g/cricket-world-cup/' },
{ title: 'Crossy Road', href: '/g/crossy-road/' },
{ title: 'Cubeshot Io', href: '/g/cubeshot-io/' },
{ title: 'Cue Billiard Club', href: '/g/cue-billiard-club/' },
{ title: 'Cut the Rope', href: '/g/cut-the-rope/' },
{ title: 'Dark Ninja', href: '/g/dark-ninja/' },
{ title: 'Dashcraft Io', href: '/g/dashcraft-io/' },
{ title: 'Dead Again', href: '/g/dead-again/' },
{ title: 'Deadshot Io', href: '/g/deadshot-io/' },
{ title: 'Deal or No Deal', href: '/g/deal-or-no-deal/' },
{ title: 'Death Run 3d', href: '/g/death-run-3d/' },
{ title: 'Deathcar Io', href: '/g/deathcar-io/' },
{ title: 'Diebrary', href: '/g/diebrary/' },
{ title: 'Dinosaur Game', href: '/g/dinosaur-game/' },
{ title: 'Dinosaurs Merge Master', href: '/g/dinosaurs-merge-master/' },
{ title: 'Doge Miner', href: '/g/doge-miner/' },
{ title: 'Doodle Jump', href: '/g/doodle-jump/' },
{ title: 'Dots and Boxes', href: '/g/dots-and-boxes/' },
{ title: 'Down the Hill', href: '/g/down-the-hill/' },
{ title: 'Draw and Escape', href: '/g/draw-and-escape/' },
{ title: 'Draw to Home 3d', href: '/g/draw-to-home-3d/' },
{ title: 'Dreadhead Parkour', href: '/g/dreadhead-parkour/' },
{ title: 'Drift Boss', href: '/g/drift-boss/' },
{ title: 'Drift Hunters', href: '/g/drift-hunters/' },
{ title: 'Drive Mad', href: '/g/drive-mad/' },
{ title: 'Drop Kick World Cup 2018', href: '/g/drop-kick-world-cup-2018/' },
{ title: 'Duck Life', href: '/g/duck-life/' },
{ title: 'Duck Life 2', href: '/g/duck-life-2/' },
{ title: 'Duck Life 3', href: '/g/duck-life-3/' },
{ title: 'Duck Life 4', href: '/g/duck-life-4/' },
{ title: 'Duck Life 5', href: '/g/duck-life-5/' },
{ title: 'Duke Dashington Remastered', href: '/g/duke-dashington-remastered/' },
{ title: 'Dunk Perfect', href: '/g/dunk-perfect/' },
{ title: 'Dunkers', href: '/g/dunkers/' },
{ title: 'Dunkers 2', href: '/g/dunkers-2/' },
{ title: 'Eggy Car', href: '/g/eggy-car/' },
{ title: 'Elastic Man', href: '/g/elastic-man/' },
{ title: 'Electron Dash', href: '/g/electron-dash/' },
{ title: 'Endless Tunnel', href: '/g/endless-tunnel/' },
{ title: 'Endless War 3', href: '/g/endless-war-3/' },
{ title: 'Eparkour Io', href: '/g/eparkour-io/' },
{ title: 'Erase Box', href: '/g/erase-box/' },
{ title: 'Escape Road', href: '/g/escape-road/' },
{ title: 'Escaperoad', href: '/g/escaperoad/' },
{ title: 'Ev Io', href: '/g/ev-io/' },
{ title: 'Extreme Run 3d', href: '/g/extreme-run-3d/' },
{ title: 'Fallguys', href: '/g/fallguys/' },
{ title: 'Farm Match Seasons', href: '/g/farm-match-seasons/' },
{ title: 'Ferge Io', href: '/g/ferge-io/' },
{ title: 'Fight Arena Online', href: '/g/fight-arena-online/' },
{ title: 'Fightz Io', href: '/g/fightz-io/' },
{ title: 'Fill Glass', href: '/g/fill-glass/' },
{ title: 'Fire Truck Rescue', href: '/g/fire-truck-rescue/' },
{ title: 'Fireboy and Watergirl 2', href: '/g/fireboy-and-watergirl-2/' },
{ title: 'Fireboy and Watergirl 3', href: '/g/fireboy-and-watergirl-3/' },
{ title: 'Fireboy and Watergirl 4', href: '/g/fireboy-and-watergirl-4/' },
{ title: 'Fireboy and Watergirl 5 Elements', href: '/g/fireboy-and-watergirl-5-elements/' },
{ title: 'Fireboy and Watergirl 6', href: '/g/fireboy-and-watergirl-6/' },
{ title: 'Fireboy and Watergirl Forest Temple', href: '/g/fireboy-and-watergirl-forest-temple/' },
{ title: 'Fishing and Lines', href: '/g/fishing-and-lines/' },
{ title: 'Fishing Frenzy', href: '/g/fishing-frenzy/' },
{ title: 'Five Nights at Freddys 2', href: '/g/five-nights-at-freddys-2/' },
{ title: 'Five Nights at Freddys 3', href: '/g/five-nights-at-freddys-3/' },
{ title: 'Five Nights at Freddys 4', href: '/g/five-nights-at-freddys-4/' },
{ title: 'Five Nights at Freddys Web', href: '/g/five-nights-at-freddys-web/' },
{ title: 'Fiveheads Soccer', href: '/g/fiveheads-soccer/' },
{ title: 'Flappy Bird', href: '/g/flappy-bird/' },
{ title: 'Flappy Dunk', href: '/g/flappy-dunk/' },
{ title: 'Fnaf Shooter', href: '/g/fnaf-shooter/' },
{ title: 'Football Legends', href: '/g/football-legends/' },
{ title: 'Football Legends 2021', href: '/g/football-legends-2021/' },
{ title: 'Football Masters', href: '/g/football-masters/' },
{ title: 'Football Run', href: '/g/football-run/' },
{ title: 'Football Strike', href: '/g/football-strike/' },
{ title: 'Football Superstars 2024', href: '/g/football-superstars-2024/' },
{ title: 'Fortnite Made in China', href: '/g/fortnite-made-in-china/' },
{ title: 'Four Color', href: '/g/four-color/' },
{ title: 'Fps Assault Shooter', href: '/g/fps-assault-shooter/' },
{ title: 'Free Kick Classic', href: '/g/free-kick-classic/' },
{ title: 'Free Kick Shooter', href: '/g/free-kick-shooter/' },
{ title: 'Friday Night Funkin', href: '/g/friday-night-funkin/' },
{ title: 'Fruit Ninja', href: '/g/fruit-ninja/' },
{ title: 'Funny Ragdoll Wrestlers', href: '/g/funny-ragdoll-wrestlers/' },
{ title: 'Funny Shooter', href: '/g/funny-shooter/' },
{ title: 'Funny Shooter 2', href: '/g/funny-shooter-2/' },
{ title: 'G Switch', href: '/g/g-switch/' },
{ title: 'G Switch 2', href: '/g/g-switch-2/' },
{ title: 'G Switch 3', href: '/g/g-switch-3/' },
{ title: 'G Switch 4', href: '/g/g-switch-4/' },
{ title: 'Gartic Io', href: '/g/gartic-io/' },
{ title: 'Gartic Phone', href: '/g/gartic-phone/' },
{ title: 'Geo Dash 2', href: '/g/geo-dash-2/' },
{ title: 'Geometry Dash', href: '/g/geometry-dash/' },
{ title: 'Geometry Dash 2', href: '/g/geometry-dash-2/' },
{ title: 'Geometry Monster', href: '/g/geometry-monster/' },
{ title: 'Get on Top', href: '/g/get-on-top/' },
{ title: 'Getaway Shootout', href: '/g/getaway-shootout/' },
{ title: 'Getting Over It', href: '/g/getting-over-it/' },
{ title: 'Giant Run 3d', href: '/g/giant-run-3d/' },
{ title: 'Gigga Io', href: '/g/gigga-io/' },
{ title: 'Goalkeeper Challenge', href: '/g/goalkeeper-challenge/' },
{ title: 'Gobdun', href: '/g/gobdun/' },
{ title: 'Gold Digger Frvr', href: '/g/gold-digger-frvr/' },
{ title: 'Golf Orbit', href: '/g/golf-orbit/' },
{ title: 'Golf Quest', href: '/g/golf-quest/' },
{ title: 'Golf Zero', href: '/g/golf-zero/' },
{ title: 'Golfparty Io', href: '/g/golfparty-io/' },
{ title: 'Grand Prix Hero', href: '/g/grand-prix-hero/' },
{ title: 'Grand Vegas Simulator', href: '/g/grand-vegas-simulator/' },
{ title: 'Granny', href: '/g/granny/' },
{ title: 'Gravity Soccer', href: '/g/gravity-soccer/' },
{ title: 'Grindcraft Remastered', href: '/g/grindcraft-remastered/' },
{ title: 'Gully Cricket', href: '/g/gully-cricket/' },
{ title: 'Gulper Io', href: '/g/gulper-io/' },
{ title: 'Gun Mayhem 2', href: '/g/gun-mayhem-2/' },
{ title: 'Gun Mayhem Redux', href: '/g/gun-mayhem-redux/' },
{ title: 'Gunmayhem', href: '/g/gunmayhem/' },
{ title: 'Gunspin', href: '/g/gunspin/' },
{ title: 'Gym Heros Fighting Game', href: '/g/gym-heros-fighting-game/' },
{ title: 'Gym Masters', href: '/g/gym-masters/' },
{ title: 'Hammer 2', href: '/g/hammer-2/' },
{ title: 'Hanger', href: '/g/hanger/' },
{ title: 'Hanger 2', href: '/g/hanger-2/' },
{ title: 'Happy Filled Glass', href: '/g/happy-filled-glass/' },
{ title: 'Happy Fishing', href: '/g/happy-fishing/' },
{ title: 'Happy Wheels', href: '/g/happy-wheels/' },
{ title: 'Hazmob Fps', href: '/g/hazmob-fps/' },
{ title: 'Head Soccer 2022', href: '/g/head-soccer-2022/' },
{ title: 'Head Soccer 2023', href: '/g/head-soccer-2023/' },
{ title: 'Head Soccer World Champion', href: '/g/head-soccer-world-champion/' },
{ title: 'Heads Arena Soccer All Stars', href: '/g/heads-arena-soccer-all-stars/' },
{ title: 'Hero Tower War', href: '/g/hero-tower-war/' },
{ title: 'Hero Wizard Save Your Girlfriend', href: '/g/hero-wizard-save-your-girlfriend/' },
{ title: 'Hexanaut Io', href: '/g/hexanaut-io/' },
{ title: 'Hill Climb on Moto Bike', href: '/g/hill-climb-on-moto-bike/' },
{ title: 'Hill Climb Racing 2', href: '/g/hill-climb-racing-2/' },
{ title: 'Hole Io', href: '/g/hole-io/' },
{ title: 'Home Pin 1', href: '/g/home-pin-1/' },
{ title: 'Home Pin 2', href: '/g/home-pin-2/' },
{ title: 'Hoop World 3d', href: '/g/hoop-world-3d/' },
{ title: 'Hop & Pop It', href: '/g/hop-&-pop-it/' },
{ title: 'House of Hazards', href: '/g/house-of-hazards/' },
{ title: 'Icy Purple Head 2', href: '/g/icy-purple-head-2/' },
{ title: 'Idle Breakout', href: '/g/idle-breakout/' },
{ title: 'Idle Football Manager', href: '/g/idle-football-manager/' },
{ title: 'Idle Gold Miner', href: '/g/idle-gold-miner/' },
{ title: 'Idle Light City', href: '/g/idle-light-city/' },
{ title: 'Idle Mining Empire', href: '/g/idle-mining-empire/' },
{ title: 'Idle Restaurant Tycoon', href: '/g/idle-restaurant-tycoon/' },
{ title: 'Idle Tree City', href: '/g/idle-tree-city/' },
{ title: 'Idle Zoo Safari Rescue', href: '/g/idle-zoo-safari-rescue/' },
{ title: 'Immaculate Grid Football', href: '/g/immaculate-grid-football/' },
{ title: 'Impossible Monster Truck', href: '/g/impossible-monster-truck/' },
{ title: 'Impossible Monster Truck Race', href: '/g/impossible-monster-truck-race/' },
{ title: 'Impossible Tic Tac Toe', href: '/g/impossible-tic-tac-toe/' },
{ title: 'Indian Truck Simulator 3d', href: '/g/indian-truck-simulator-3d/' },
{ title: 'Infinite Soccer', href: '/g/infinite-soccer/' },
{ title: 'International Super Animal Soccer', href: '/g/international-super-animal-soccer/' },
{ title: 'Iron Snout', href: '/g/iron-snout/' },
{ title: 'Jacksmith', href: '/g/jacksmith/' },
{ title: 'James Gun', href: '/g/james-gun/' },
{ title: 'Jelly Truck', href: '/g/jelly-truck/' },
{ title: 'Jetpack Joyride', href: '/g/jetpack-joyride/' },
{ title: 'Jewels Blitz 5', href: '/g/jewels-blitz-5/' },
{ title: 'Johnny Trigger', href: '/g/johnny-trigger/' },
{ title: 'Johnny Upgrade', href: '/g/johnny-upgrade/' },
{ title: 'Johny Revenge', href: '/g/johny-revenge/' },
{ title: 'Jollyworld', href: '/g/jollyworld/' },
{ title: 'Jungle Td', href: '/g/jungle-td/' },
{ title: 'Just Fall Lol', href: '/g/just-fall-lol/' },
{ title: 'Just Park It 11', href: '/g/just-park-it-11/' },
{ title: 'Just Park It 12', href: '/g/just-park-it-12/' },
{ title: 'Kart Fight Io', href: '/g/kart-fight-io/' },
{ title: 'Kart Race 3d', href: '/g/kart-race-3d/' },
{ title: 'Kawaii Dressup', href: '/g/kawaii-dressup/' },
{ title: 'King of Crabs', href: '/g/king-of-crabs/' },
{ title: 'Kingpin Bowling', href: '/g/kingpin-bowling/' },
{ title: 'Kirka Io', href: '/g/kirka-io/' },
{ title: 'Knight Hero Adventure Idle Rpg', href: '/g/knight-hero-adventure-idle-rpg/' },
{ title: 'Kour Io', href: '/g/kour-io/' },
{ title: 'Krunker Io', href: '/g/krunker-io/' },
{ title: 'Lands of Blight', href: '/g/lands-of-blight/' },
{ title: 'Leader Strike', href: '/g/leader-strike/' },
{ title: 'Learn to Fly', href: '/g/learn-to-fly/' },
{ title: 'Learntofly2', href: '/g/learntofly2/' },
{ title: 'Lethal Sniper 3d Army Soldier', href: '/g/lethal-sniper-3d-army-soldier/' },
{ title: 'Level Devil', href: '/g/level-devil/' },
{ title: 'Little Master Cricket', href: '/g/little-master-cricket/' },
{ title: 'Lolbeans Io', href: '/g/lolbeans-io/' },
{ title: 'Lolshot Io', href: '/g/lolshot-io/' },
{ title: 'Lovely Fox', href: '/g/lovely-fox/' },
{ title: 'Ludo Multiplayer', href: '/g/ludo-multiplayer/' },
{ title: 'Lurkers Io', href: '/g/lurkers-io/' },
{ title: 'Mad Cars Racing and Crash', href: '/g/mad-cars-racing-and-crash/' },
{ title: 'Mad Day', href: '/g/mad-day/' },
{ title: 'Mad Guns Battle Royale', href: '/g/mad-guns-battle-royale/' },
{ title: 'Mad Shark', href: '/g/mad-shark/' },
{ title: 'Mad Truck Challenge', href: '/g/mad-truck-challenge/' },
{ title: 'Madalin Cars Multiplayer', href: '/g/madalin-cars-multiplayer/' },
{ title: 'Madalin Stunt Cars 2', href: '/g/madalin-stunt-cars-2/' },
{ title: 'Madalin Stunt Cars 3', href: '/g/madalin-stunt-cars-3/' },
{ title: 'Madzoong', href: '/g/madzoong/' },
{ title: 'Mafia Wars', href: '/g/mafia-wars/' },
{ title: 'Marble Dash', href: '/g/marble-dash/' },
{ title: 'Marbles Sorting', href: '/g/marbles-sorting/' },
{ title: 'Masked Forces', href: '/g/masked-forces/' },
{ title: 'Master Checkers', href: '/g/master-checkers/' },
{ title: 'Maze Path of Light', href: '/g/maze-path-of-light/' },
{ title: 'Maze Planet 3d', href: '/g/maze-planet-3d/' },
{ title: 'Merc Zone', href: '/g/merc-zone/' },
{ title: 'Merge Cakes', href: '/g/merge-cakes/' },
{ title: 'Merge Cyber Racers', href: '/g/merge-cyber-racers/' },
{ title: 'Merge Harvest', href: '/g/merge-harvest/' },
{ title: 'Merge Party', href: '/g/merge-party/' },
{ title: 'Merge Round Racers', href: '/g/merge-round-racers/' },
{ title: 'Mine Craft Io', href: '/g/mine-craft-io/' },
{ title: 'Minecraft Builds', href: '/g/minecraft-builds/' },
{ title: 'Minecraft Case Simulator', href: '/g/minecraft-case-simulator/' },
{ title: 'Minecraft Classic', href: '/g/minecraft-classic/' },
{ title: 'Minesweeper', href: '/g/minesweeper/' },
{ title: 'Mini Golf 18', href: '/g/mini-golf-18/' },
{ title: 'Mini Putt', href: '/g/mini-putt/' },
{ title: 'Minibattles', href: '/g/minibattles/' },
{ title: 'Mob City', href: '/g/mob-city/' },
{ title: 'Money Movers', href: '/g/money-movers/' },
{ title: 'Money Movers 2', href: '/g/money-movers-2/' },
{ title: 'Money Movers 3', href: '/g/money-movers-3/' },
{ title: 'Money Roller', href: '/g/money-roller/' },
{ title: 'Money Rush', href: '/g/money-rush/' },
{ title: 'Monkey Mart', href: '/g/monkey-mart/' },
{ title: 'Monster Truck Arena', href: '/g/monster-truck-arena/' },
{ title: 'Monster Truck Vs Zombie', href: '/g/monster-truck-vs-zombie/' },
{ title: 'Monsters Wheels Special', href: '/g/monsters-wheels-special/' },
{ title: 'Moomoo Io Sandbox', href: '/g/moomoo-io-sandbox/' },
{ title: 'Mosaic Puzzle Art', href: '/g/mosaic-puzzle-art/' },
{ title: 'Moto Maniac', href: '/g/moto-maniac/' },
{ title: 'Moto Maniac 2', href: '/g/moto-maniac-2/' },
{ title: 'Moto Maniac 3', href: '/g/moto-maniac-3/' },
{ title: 'Moto Trial Racing 2', href: '/g/moto-trial-racing-2/' },
{ title: 'Moto X3m', href: '/g/moto-x3m/' },
{ title: 'Moto X3m 2', href: '/g/moto-x3m-2/' },
{ title: 'Moto X3m 4 Winter', href: '/g/moto-x3m-4-winter/' },
{ title: 'Moto X3m 5 Pool Party', href: '/g/moto-x3m-5-pool-party/' },
{ title: 'Moto X3m 6 Spooky Land', href: '/g/moto-x3m-6-spooky-land/' },
{ title: 'Moto X3m Pool Party', href: '/g/moto-x3m-pool-party/' },
{ title: 'Moving Truck Bounty', href: '/g/moving-truck-bounty/' },
{ title: 'Mr Bullet', href: '/g/mr-bullet/' },
{ title: 'Mutazone', href: '/g/mutazone/' },
{ title: 'My Perfect Hotel', href: '/g/my-perfect-hotel/' },
{ title: 'My Pony My Little Race', href: '/g/my-pony-my-little-race/' },
{ title: 'Mystical Birdlink', href: '/g/mystical-birdlink/' },
{ title: 'Nba Jam', href: '/g/nba-jam/' },
{ title: 'Neon War', href: '/g/neon-war/' },
{ title: 'Nightpoint Io', href: '/g/nightpoint-io/' },
{ title: 'Ninja Bamboo Assassin', href: '/g/ninja-bamboo-assassin/' },
{ title: 'Ninja Cat Exploit', href: '/g/ninja-cat-exploit/' },
{ title: 'Ninja Time', href: '/g/ninja-time/' },
{ title: 'Noob Hook', href: '/g/noob-hook/' },
{ title: 'Noob Steve Parkour', href: '/g/noob-steve-parkour/' },
{ title: 'Noob Vs Zombies', href: '/g/noob-vs-zombies/' },
{ title: 'Nugget Royale Io', href: '/g/nugget-royale-io/' },
{ title: 'Nuggetroyale Io', href: '/g/nuggetroyale-io/' },
{ title: 'Odd Bot Out', href: '/g/odd-bot-out/' },
{ title: 'Off Road Rain Cargo Simulator', href: '/g/off-road-rain-cargo-simulator/' },
{ title: 'Only 3d Parkour', href: '/g/only-3d-parkour/' },
{ title: 'Only Up', href: '/g/only-up/' },
{ title: 'Only Up 2', href: '/g/only-up-2/' },
{ title: 'Orbital Survivor', href: '/g/orbital-survivor/' },
{ title: 'Ovo', href: '/g/ovo/' },
{ title: 'Ovo 3 Dimensions', href: '/g/ovo-3-dimensions/' },
{ title: 'Ovo Classic', href: '/g/ovo-classic/' },
{ title: 'Ovo2', href: '/g/ovo2/' },
{ title: 'Pac Man World', href: '/g/pac-man-world/' },
{ title: 'Pack a Bag', href: '/g/pack-a-bag/' },
{ title: 'Pacman', href: '/g/pacman/' },
{ title: 'Paint Strike', href: '/g/paint-strike/' },
{ title: 'Panda Bubble Shooter', href: '/g/panda-bubble-shooter/' },
{ title: 'Panda Simulator 3d', href: '/g/panda-simulator-3d/' },
{ title: 'Papa Louie', href: '/g/papa-louie/' },
{ title: 'Papa Louie 2', href: '/g/papa-louie-2/' },
{ title: 'Papa Louie 3', href: '/g/papa-louie-3/' },
{ title: 'Papas Bakeria', href: '/g/papas-bakeria/' },
{ title: 'Papas Burgeria', href: '/g/papas-burgeria/' },
{ title: 'Papas Cheeseria', href: '/g/papas-cheeseria/' },
{ title: 'Papas Cup Cakeria', href: '/g/papas-cup-cakeria/' },
{ title: 'Papas Donuteria', href: '/g/papas-donuteria/' },
{ title: 'Papas Freezeria', href: '/g/papas-freezeria/' },
{ title: 'Papas Hot Doggeria', href: '/g/papas-hot-doggeria/' },
{ title: 'Papas Pastaria', href: '/g/papas-pastaria/' },
{ title: 'Papas Pizzaria', href: '/g/papas-pizzaria/' },
{ title: 'Papas Scooperia', href: '/g/papas-scooperia/' },
{ title: 'Papas Sushiria', href: '/g/papas-sushiria/' },
{ title: 'Papas Taco Mia', href: '/g/papas-taco-mia/' },
{ title: 'Papas Wingeria', href: '/g/papas-wingeria/' },
{ title: 'Paper Fighter 3d', href: '/g/paper-fighter-3d/' },
{ title: 'Paper Io 2', href: '/g/paper-io-2/' },
{ title: 'Paper Io 3', href: '/g/paper-io-3/' },
{ title: 'Paper Minecraft', href: '/g/paper-minecraft/' },
{ title: 'Park Out', href: '/g/park-out/' },
{ title: 'Parking Fury', href: '/g/parking-fury/' },
{ title: 'Parking Fury 2', href: '/g/parking-fury-2/' },
{ title: 'Parking Fury 3d', href: '/g/parking-fury-3d/' },
{ title: 'Parking Fury 3d Beach City', href: '/g/parking-fury-3d-beach-city/' },
{ title: 'Parking Fury 3d Bounty Hunter', href: '/g/parking-fury-3d-bounty-hunter/' },
{ title: 'Parking Fury 3d Night Thief', href: '/g/parking-fury-3d-night-thief/' },
{ title: 'Parking Mania', href: '/g/parking-mania/' },
{ title: 'Parkour First Person', href: '/g/parkour-first-person/' },
{ title: 'Parkour Race', href: '/g/parkour-race/' },
{ title: 'Penalty Fever', href: '/g/penalty-fever/' },
{ title: 'Penalty Kicks', href: '/g/penalty-kicks/' },
{ title: 'Penalty Shooters', href: '/g/penalty-shooters/' },
{ title: 'Penalty Shooters 2', href: '/g/penalty-shooters-2/' },
{ title: 'Penalty Shooters 3', href: '/g/penalty-shooters-3/' },
{ title: 'Penalty Superstar', href: '/g/penalty-superstar/' },
{ title: 'Peppa Pig Basketball', href: '/g/peppa-pig-basketball/' },
{ title: 'Perfect Dunk', href: '/g/perfect-dunk/' },
{ title: 'Petz Lol', href: '/g/petz-lol/' },
{ title: 'Ping Pong Chaos', href: '/g/ping-pong-chaos/' },
{ title: 'Ping Pong Go', href: '/g/ping-pong-go/' },
{ title: 'Pixel Gun 3d', href: '/g/pixel-gun-3d/' },
{ title: 'Pixel Gun Apocalypse 2', href: '/g/pixel-gun-apocalypse-2/' },
{ title: 'Pixel Gun Survival', href: '/g/pixel-gun-survival/' },
{ title: 'Pixel Smash Duel', href: '/g/pixel-smash-duel/' },
{ title: 'Pizza Tower', href: '/g/pizza-tower/' },
{ title: 'Plantsvszombies', href: '/g/plantsvszombies/' },
{ title: 'Play Icy Purple Head 3', href: '/g/play-icy-purple-head-3/' },
{ title: 'Pony Dressup 2', href: '/g/pony-dressup-2/' },
{ title: 'Pool 8 Ball Mania', href: '/g/pool-8-ball-mania/' },
{ title: 'Pool Club', href: '/g/pool-club/' },
{ title: 'Poop Clicker 3', href: '/g/poop-clicker-3/' },
{ title: 'Poor Bunny', href: '/g/poor-bunny/' },
{ title: 'Pop It Master', href: '/g/pop-it-master/' },
{ title: 'Pou', href: '/g/pou/' },
{ title: 'President Simulator', href: '/g/president-simulator/' },
{ title: 'Prismo Coloring', href: '/g/prismo-coloring/' },
{ title: 'Pro Bowling', href: '/g/pro-bowling/' },
{ title: 'Pudding Monsters', href: '/g/pudding-monsters/' },
{ title: 'Punch Hero', href: '/g/punch-hero/' },
{ title: 'Punchers', href: '/g/punchers/' },
{ title: 'Push the Box', href: '/g/push-the-box/' },
{ title: 'Push the Box 3d', href: '/g/push-the-box-3d/' },
{ title: 'Qb Legend', href: '/g/qb-legend/' },
{ title: 'Quake', href: '/g/quake/' },
{ title: 'Rabbit Samurai', href: '/g/rabbit-samurai/' },
{ title: 'Rabbit Samurai 2', href: '/g/rabbit-samurai-2/' },
{ title: 'Raft Wars', href: '/g/raft-wars/' },
{ title: 'Raft Wars 2', href: '/g/raft-wars-2/' },
{ title: 'Ragdoll Fight', href: '/g/ragdoll-fight/' },
{ title: 'Ragdoll Soccer 2 Players', href: '/g/ragdoll-soccer-2-players/' },
{ title: 'Rainbow Parkour', href: '/g/rainbow-parkour/' },
{ title: 'Rally Champion', href: '/g/rally-champion/' },
{ title: 'Rally Point 3', href: '/g/rally-point-3/' },
{ title: 'Real Flying Truck Simulator 3d', href: '/g/real-flying-truck-simulator-3d/' },
{ title: 'Real Football', href: '/g/real-football/' },
{ title: 'Real Garbage Truck', href: '/g/real-garbage-truck/' },
{ title: 'Real Parkour Simulator', href: '/g/real-parkour-simulator/' },
{ title: 'Realistic City Parking', href: '/g/realistic-city-parking/' },
{ title: 'Recoil', href: '/g/recoil/' },
{ title: 'Red Ball 4', href: '/g/red-ball-4/' },
{ title: 'Red Driver 5', href: '/g/red-driver-5/' },
{ title: 'Repuls Io', href: '/g/repuls-io/' },
{ title: 'Retro Bowl', href: '/g/retro-bowl/' },
{ title: 'Retro Bowl College', href: '/g/retro-bowl-college/' },
{ title: 'Return Man 2', href: '/g/return-man-2/' },
{ title: 'Return Man 2 Zombies', href: '/g/return-man-2-zombies/' },
{ title: 'Riddle School 5', href: '/g/riddle-school-5/' },
{ title: 'Riddle Transfer 2', href: '/g/riddle-transfer-2/' },
{ title: 'Rise of Neon Square', href: '/g/rise-of-neon-square/' },
{ title: 'Roblox', href: '/g/roblox/' },
{ title: 'Rocket League', href: '/g/rocket-league/' },
{ title: 'Rocket Pult', href: '/g/rocket-pult/' },
{ title: 'Rocket Soccer Derby', href: '/g/rocket-soccer-derby/' },
{ title: 'Rogue Dunk', href: '/g/rogue-dunk/' },
{ title: 'Rolling Ball 3d', href: '/g/rolling-ball-3d/' },
{ title: 'Rolly Vortex', href: '/g/rolly-vortex/' },
{ title: 'Rolly Vortex Ball', href: '/g/rolly-vortex-ball/' },
{ title: 'Rooftop Snipers', href: '/g/rooftop-snipers/' },
{ title: 'Rooftop Snipers 2', href: '/g/rooftop-snipers-2/' },
{ title: 'Roper', href: '/g/roper/' },
{ title: 'Rowdy Wrestling', href: '/g/rowdy-wrestling/' },
{ title: 'Royal Pool', href: '/g/royal-pool/' },
{ title: 'Royale Dudes', href: '/g/royale-dudes/' },
{ title: 'Rugby Rush', href: '/g/rugby-rush/' },
{ title: 'Run 3 Editor', href: '/g/run-3-editor/' },
{ title: 'Run 3d', href: '/g/run-3d/' },
{ title: 'Running Fred', href: '/g/running-fred/' },
{ title: 'Rusher Crusher', href: '/g/rusher-crusher/' },
{ title: 'Sandstrike Io', href: '/g/sandstrike-io/' },
{ title: 'Sausage Flip', href: '/g/sausage-flip/' },
{ title: 'Save the Doge', href: '/g/save-the-doge/' },
{ title: 'Scenexe Io', href: '/g/scenexe-io/' },
{ title: 'Scrap Divers', href: '/g/scrap-divers/' },
{ title: 'Scrap Metal 3 Infernal Trap', href: '/g/scrap-metal-3-infernal-trap/' },
{ title: 'Shady Bears', href: '/g/shady-bears/' },
{ title: 'Shape Fold', href: '/g/shape-fold/' },
{ title: 'Shape Fold Animals', href: '/g/shape-fold-animals/' },
{ title: 'Shark Io', href: '/g/shark-io/' },
{ title: 'Shell Shockers', href: '/g/shell-shockers/' },
{ title: 'Ships 3d', href: '/g/ships-3d/' },
{ title: 'Shoot Stickman', href: '/g/shoot-stickman/' },
{ title: 'Shootz', href: '/g/shootz/' },
{ title: 'Short Ride', href: '/g/short-ride/' },
{ title: 'Simplyup Io', href: '/g/simplyup-io/' },
{ title: 'Sink It', href: '/g/sink-it/' },
{ title: 'Ski King 2024', href: '/g/ski-king-2024/' },
{ title: 'Skibidi Battle Toilets Attack', href: '/g/skibidi-battle-toilets-attack/' },
{ title: 'Skibidi Shooter', href: '/g/skibidi-shooter/' },
{ title: 'Skibidi Toilet Rampage', href: '/g/skibidi-toilet-rampage/' },
{ title: 'Skiing Fred', href: '/g/skiing-fred/' },
{ title: 'Skillfite Io', href: '/g/skillfite-io/' },
{ title: 'Skyblock', href: '/g/skyblock/' },
{ title: 'Slime Laboratory', href: '/g/slime-laboratory/' },
{ title: 'Slime Road', href: '/g/slime-road/' },
{ title: 'Slime Rush Td', href: '/g/slime-rush-td/' },
{ title: 'Sling Kong', href: '/g/sling-kong/' },
{ title: 'Slope', href: '/g/slope/' },
{ title: 'Slope 2', href: '/g/slope-2/' },
{ title: 'Slope 2 Player', href: '/g/slope-2-player/' },
{ title: 'Slope 3', href: '/g/slope-3/' },
{ title: 'Slope Ball', href: '/g/slope-ball/' },
{ title: 'Slope City', href: '/g/slope-city/' },
{ title: 'Slope Game', href: '/g/slope-game/' },
{ title: 'Slope Spooky', href: '/g/slope-spooky/' },
{ title: 'Slope Tunnel', href: '/g/slope-tunnel/' },
{ title: 'Slopey', href: '/g/slopey/' },
{ title: 'Smash and Hide', href: '/g/smash-and-hide/' },
{ title: 'Smash Karts', href: '/g/smash-karts/' },
{ title: 'Smashkarts Io', href: '/g/smashkarts-io/' },
{ title: 'Smashy Duo', href: '/g/smashy-duo/' },
{ title: 'Snail Bob 5 Love Story', href: '/g/snail-bob-5-love-story/' },
{ title: 'Snail Bob 6 Winter Story', href: '/g/snail-bob-6-winter-story/' },
{ title: 'Snail Bob 7 Fantasy Story', href: '/g/snail-bob-7-fantasy-story/' },
{ title: 'Snail Bob 8 Island Story', href: '/g/snail-bob-8-island-story/' },
{ title: 'Snake', href: '/g/snake/' },
{ title: 'Snake Clash', href: '/g/snake-clash/' },
{ title: 'Snake Io', href: '/g/snake-io/' },
{ title: 'Snake   Mlg Edition', href: '/g/snake-mlg-edition/' },
{ title: 'Snay Io', href: '/g/snay-io/' },
{ title: 'Sniper 3d', href: '/g/sniper-3d/' },
{ title: 'Sniper Shot', href: '/g/sniper-shot/' },
{ title: 'Sniper Shot Bullet Time', href: '/g/sniper-shot-bullet-time/' },
{ title: 'Snipey Io', href: '/g/snipey-io/' },
{ title: 'Snow Rider 3d', href: '/g/snow-rider-3d/' },
{ title: 'Snowball Io', href: '/g/snowball-io/' },
{ title: 'Snowboard King 2024', href: '/g/snowboard-king-2024/' },
{ title: 'Soccer Bros', href: '/g/soccer-bros/' },
{ title: 'Soccer Clicker', href: '/g/soccer-clicker/' },
{ title: 'Soccer Dash', href: '/g/soccer-dash/' },
{ title: 'Soccer Duel', href: '/g/soccer-duel/' },
{ title: 'Soccer Heads', href: '/g/soccer-heads/' },
{ title: 'Soccer Legends 2021', href: '/g/soccer-legends-2021/' },
{ title: 'Soccer Merge', href: '/g/soccer-merge/' },
{ title: 'Soccer Random', href: '/g/soccer-random/' },
{ title: 'Soccer Skills Champions League', href: '/g/soccer-skills-champions-league/' },
{ title: 'Soccer Skills Euro Cup', href: '/g/soccer-skills-euro-cup/' },
{ title: 'Soccer Skills Euro Cup 2021', href: '/g/soccer-skills-euro-cup-2021/' },
{ title: 'Soccer Skills World Cup', href: '/g/soccer-skills-world-cup/' },
{ title: 'Sonic the Hedgehog Remastere', href: '/g/sonic-the-hedgehog-remastere/' },
{ title: 'Space Is Key', href: '/g/space-is-key/' },
{ title: 'Space Major Miner', href: '/g/space-major-miner/' },
{ title: 'Speed Pool King', href: '/g/speed-pool-king/' },
{ title: 'Spider Solitaire', href: '/g/spider-solitaire/' },
{ title: 'Sport Minibattles', href: '/g/sport-minibattles/' },
{ title: 'Sports Heads Soccer', href: '/g/sports-heads-soccer/' },
{ title: 'Sprinter', href: '/g/sprinter/' },
{ title: 'Stabfish 2', href: '/g/stabfish-2/' },
{ title: 'Stabfish Io', href: '/g/stabfish-io/' },
{ title: 'Stack Bump 3d', href: '/g/stack-bump-3d/' },
{ title: 'Stair Race 3d', href: '/g/stair-race-3d/' },
{ title: 'Starblast', href: '/g/starblast/' },
{ title: 'Stealing the Diamond', href: '/g/stealing-the-diamond/' },
{ title: 'Stick Archers Battle', href: '/g/stick-archers-battle/' },
{ title: 'Stick Defenders', href: '/g/stick-defenders/' },
{ title: 'Stick Duel Battle', href: '/g/stick-duel-battle/' },
{ title: 'Stick Fight the Chaos', href: '/g/stick-fight-the-chaos/' },
{ title: 'Stick Merge', href: '/g/stick-merge/' },
{ title: 'Stickbattle Lo', href: '/g/stickbattle-lo/' },
{ title: 'Stickman Army the Resistance', href: '/g/stickman-army-the-resistance/' },
{ title: 'Stickman Boost', href: '/g/stickman-boost/' },
{ title: 'Stickman Boost 2', href: '/g/stickman-boost-2/' },
{ title: 'Stickman Crazy Box', href: '/g/stickman-crazy-box/' },
{ title: 'Stickman Fight Pro', href: '/g/stickman-fight-pro/' },
{ title: 'Stickman Fight Ragdoll', href: '/g/stickman-fight-ragdoll/' },
{ title: 'Stickman Fighter Mega Brawl', href: '/g/stickman-fighter-mega-brawl/' },
{ title: 'Stickman Golf', href: '/g/stickman-golf/' },
{ title: 'Stickman Hook', href: '/g/stickman-hook/' },
{ title: 'Stickman Ragdoll Crash Fun', href: '/g/stickman-ragdoll-crash-fun/' },
{ title: 'Stickman Tennis 3d', href: '/g/stickman-tennis-3d/' },
{ title: 'Stickman Vs Zombies', href: '/g/stickman-vs-zombies/' },
{ title: 'Stickman Warriors', href: '/g/stickman-warriors/' },
{ title: 'Stock Car Hero', href: '/g/stock-car-hero/' },
{ title: 'Street Ball Jam', href: '/g/street-ball-jam/' },
{ title: 'Street Freekick 3d', href: '/g/street-freekick-3d/' },
{ title: 'Stupid Zombies 2', href: '/g/stupid-zombies-2/' },
{ title: 'Subway Princess Runner', href: '/g/subway-princess-runner/' },
{ title: 'Subway Surfers', href: '/g/subway-surfers/' },
{ title: 'Subway Surfers Bali', href: '/g/subway-surfers-bali/' },
{ title: 'Subway Surfers Hawaii', href: '/g/subway-surfers-hawaii/' },
{ title: 'Subway Surfers New York', href: '/g/subway-surfers-new-york/' },
{ title: 'Subway Surfers San Francisco', href: '/g/subway-surfers-san-francisco/' },
{ title: 'Subway Surfers Zurich', href: '/g/subway-surfers-zurich/' },
{ title: 'Sugar Shock', href: '/g/sugar-shock/' },
{ title: 'Suika Game', href: '/g/suika-game/' },
{ title: 'Sumo Party', href: '/g/sumo-party/' },
{ title: 'Super Bike the Champion', href: '/g/super-bike-the-champion/' },
{ title: 'Super Cowboy Running', href: '/g/super-cowboy-running/' },
{ title: 'Super Falling Fred', href: '/g/super-falling-fred/' },
{ title: 'Super Fowlst', href: '/g/super-fowlst/' },
{ title: 'Super Hexbee Merger', href: '/g/super-hexbee-merger/' },
{ title: 'Super Liquid Soccer', href: '/g/super-liquid-soccer/' },
{ title: 'Super Mario 64', href: '/g/super-mario-64/' },
{ title: 'Super Mario Bros', href: '/g/super-mario-bros/' },
{ title: 'Super Mx   the Champion', href: '/g/super-mx-the-champion/' },
{ title: 'Super Onion Boy', href: '/g/super-onion-boy/' },
{ title: 'Super Santa Kicker', href: '/g/super-santa-kicker/' },
{ title: 'Super Tunnel Rush', href: '/g/super-tunnel-rush/' },
{ title: 'Superbattle 2', href: '/g/superbattle-2/' },
{ title: 'Superbike Hero', href: '/g/superbike-hero/' },
{ title: 'Superhot', href: '/g/superhot/' },
{ title: 'Supernova Game', href: '/g/supernova-game/' },
{ title: 'Surviv Io', href: '/g/surviv-io/' },
{ title: 'Survivor in Rainbow Monster', href: '/g/survivor-in-rainbow-monster/' },
{ title: 'Swat Force Vs Terrorists', href: '/g/swat-force-vs-terrorists/' },
{ title: 'Swimming Pro', href: '/g/swimming-pro/' },
{ title: 'Table Tennis Ultimate Tournament', href: '/g/table-tennis-ultimate-tournament/' },
{ title: 'Table Tennis World Tour', href: '/g/table-tennis-world-tour/' },
{ title: 'Tag 2', href: '/g/tag-2/' },
{ title: 'Taming Io', href: '/g/taming-io/' },
{ title: 'Tank Battle Io', href: '/g/tank-battle-io/' },
{ title: 'Tank Trouble', href: '/g/tank-trouble/' },
{ title: 'Tank Trouble 2', href: '/g/tank-trouble-2/' },
{ title: 'Tanuki Sunset', href: '/g/tanuki-sunset/' },
{ title: 'Tap Tap Shots', href: '/g/tap-tap-shots/' },
{ title: 'Temple Run 2', href: '/g/temple-run-2/' },
{ title: 'Tennis Hero', href: '/g/tennis-hero/' },
{ title: 'Tennis Masters', href: '/g/tennis-masters/' },
{ title: 'Tennis Open 2020', href: '/g/tennis-open-2020/' },
{ title: 'Tetra Blocks', href: '/g/tetra-blocks/' },
{ title: 'Tetris', href: '/g/tetris/' },
{ title: 'Tetris 99', href: '/g/tetris-99/' },
{ title: 'the Backrooms', href: '/g/the-backrooms/' },
{ title: 'the Backrooms 3d', href: '/g/the-backrooms-3d/' },
{ title: 'the Bowling Club', href: '/g/the-bowling-club/' },
{ title: 'the Final Earth', href: '/g/the-final-earth/' },
{ title: 'the Final Earth 2', href: '/g/the-final-earth-2/' },
{ title: 'the Fish Master', href: '/g/the-fish-master/' },
{ title: 'the Heist', href: '/g/the-heist/' },
{ title: 'the Impossible Quiz', href: '/g/the-impossible-quiz/' },
{ title: 'the Impossible Quiz 2', href: '/g/the-impossible-quiz-2/' },
{ title: 'the Little Giant', href: '/g/the-little-giant/' },
{ title: 'the Spear Stickman', href: '/g/the-spear-stickman/' },
{ title: 'the Worlds Hardest Game', href: '/g/the-worlds-hardest-game/' },
{ title: 'the Worlds Hardest Game 3', href: '/g/the-worlds-hardest-game-3/' },
{ title: 'There Is No Game', href: '/g/there-is-no-game/' },
{ title: 'Thumb Fighter', href: '/g/thumb-fighter/' },
{ title: 'Tic Tac Toe', href: '/g/tic-tac-toe/' },
{ title: 'Timberman', href: '/g/timberman/' },
{ title: 'Time Shooter 2', href: '/g/time-shooter-2/' },
{ title: 'Time Shooter 3', href: '/g/time-shooter-3/' },
{ title: 'Time Shooter 3 Swat', href: '/g/time-shooter-3-swat/' },
{ title: 'Tiny Fishing', href: '/g/tiny-fishing/' },
{ title: 'Tinytownracing', href: '/g/tinytownracing/' },
{ title: 'Tomb of the Mask', href: '/g/tomb-of-the-mask/' },
{ title: 'Tomb Runner', href: '/g/tomb-runner/' },
{ title: 'Top Speed Racing 3d', href: '/g/top-speed-racing-3d/' },
{ title: 'Toss the Turtle', href: '/g/toss-the-turtle/' },
{ title: 'Total Recoil', href: '/g/total-recoil/' },
{ title: 'Touchdown Rush', href: '/g/touchdown-rush/' },
{ title: 'Touchdowners', href: '/g/touchdowners/' },
{ title: 'Tower Crash 3d', href: '/g/tower-crash-3d/' },
{ title: 'Tower Defense 2d', href: '/g/tower-defense-2d/' },
{ title: 'Tower of Destiny', href: '/g/tower-of-destiny/' },
{ title: 'Traffic Control', href: '/g/traffic-control/' },
{ title: 'Traffic Escape', href: '/g/traffic-escape/' },
{ title: 'Traffic Mania', href: '/g/traffic-mania/' },
{ title: 'Traffic Rider', href: '/g/traffic-rider/' },
{ title: 'Traffic Rush', href: '/g/traffic-rush/' },
{ title: 'Trial Xtreme', href: '/g/trial-xtreme/' },
{ title: 'Tribals Io', href: '/g/tribals-io/' },
{ title: 'Tricksplit Io', href: '/g/tricksplit-io/' },
{ title: 'Truck Loader 2', href: '/g/truck-loader-2/' },
{ title: 'Truck Loader 5', href: '/g/truck-loader-5/' },
{ title: 'Truck Traffic', href: '/g/truck-traffic/' },
{ title: 'Tube Clicker', href: '/g/tube-clicker/' },
{ title: 'Tube Jumpers', href: '/g/tube-jumpers/' },
{ title: 'Tunnel Rush', href: '/g/tunnel-rush/' },
{ title: 'Tunnel Rush 2', href: '/g/tunnel-rush-2/' },
{ title: 'Turn Turn', href: '/g/turn-turn/' },
{ title: 'Two Ball 3d', href: '/g/two-ball-3d/' },
{ title: 'Two Ball 3d Dark', href: '/g/two-ball-3d-dark/' },
{ title: 'Two Neon Boxes', href: '/g/two-neon-boxes/' },
{ title: 'Two Tunnel 3d', href: '/g/two-tunnel-3d/' },
{ title: 'Ultimate Boxing', href: '/g/ultimate-boxing/' },
{ title: 'Ultimate Offroad Simulator', href: '/g/ultimate-offroad-simulator/' },
{ title: 'Ultimate Swish', href: '/g/ultimate-swish/' },
{ title: 'Unicycle Hero', href: '/g/unicycle-hero/' },
{ title: 'Unicycle Legend', href: '/g/unicycle-legend/' },
{ title: 'Uno', href: '/g/uno/' },
{ title: 'Venge Io', href: '/g/venge-io/' },
{ title: 'Vex 3', href: '/g/vex-3/' },
{ title: 'Vex 4', href: '/g/vex-4/' },
{ title: 'Vex 5', href: '/g/vex-5/' },
{ title: 'Vex 6', href: '/g/vex-6/' },
{ title: 'Vex 7', href: '/g/vex-7/' },
{ title: 'Vex 8', href: '/g/vex-8/' },
{ title: 'Vex X3m', href: '/g/vex-x3m/' },
{ title: 'Village Craft', href: '/g/village-craft/' },
{ title: 'Volley Random', href: '/g/volley-random/' },
{ title: 'Volleyball', href: '/g/volleyball/' },
{ title: 'Voxiom Io', href: '/g/voxiom-io/' },
{ title: 'War of Caribbean Pirates', href: '/g/war-of-caribbean-pirates/' },
{ title: 'Water Color Sort', href: '/g/water-color-sort/' },
{ title: 'Water Polo Ragdoll', href: '/g/water-polo-ragdoll/' },
{ title: 'Webecomewhatwebehold', href: '/g/webecomewhatwebehold/' },
{ title: 'West Frontier Sharpshooter 3d', href: '/g/west-frontier-sharpshooter-3d/' },
{ title: 'Western Cowboy Run', href: '/g/western-cowboy-run/' },
{ title: 'Wheelie Bike', href: '/g/wheelie-bike/' },
{ title: 'Wheely 2', href: '/g/wheely-2/' },
{ title: 'Wheely 3', href: '/g/wheely-3/' },
{ title: 'Wheely 4 Time Travel', href: '/g/wheely-4-time-travel/' },
{ title: 'Wheely 5', href: '/g/wheely-5/' },
{ title: 'Wheely 6 Fairytale', href: '/g/wheely-6-fairytale/' },
{ title: 'Wheely 7 Detective', href: '/g/wheely-7-detective/' },
{ title: 'Wheely 8 Aliens', href: '/g/wheely-8-aliens/' },
{ title: 'Wheres My Cat', href: '/g/wheres-my-cat/' },
{ title: 'Wizard Mike', href: '/g/wizard-mike/' },
{ title: 'Wonderputt', href: '/g/wonderputt/' },
{ title: 'Wood Blocks 3d', href: '/g/wood-blocks-3d/' },
{ title: 'Woodoku Block Puzzle', href: '/g/woodoku-block-puzzle/' },
{ title: 'Word City Crossed', href: '/g/word-city-crossed/' },
{ title: 'Word Slide', href: '/g/word-slide/' },
{ title: 'Wordle', href: '/g/wordle/' },
{ title: 'Wordle Infinite', href: '/g/wordle-infinite/' },
{ title: 'Wordle Unlimited', href: '/g/wordle-unlimited/' },
{ title: 'Words Search Classic Edition', href: '/g/words-search-classic-edition/' },
{ title: 'Worlds Hardest Game 2', href: '/g/worlds-hardest-game-2/' },
{ title: 'Wormate Io', href: '/g/wormate-io/' },
{ title: 'Wrassling', href: '/g/wrassling/' },
{ title: 'Wrestle Bros', href: '/g/wrestle-bros/' },
{ title: 'X Trial Racing', href: '/g/x-trial-racing/' },
{ title: 'Yahoo Tennis', href: '/g/yahoo-tennis/' },
{ title: 'Yarn Untangle', href: '/g/yarn-untangle/' },
{ title: 'Yohoho Io', href: '/g/yohoho-io/' },
{ title: 'Zeepkist Crash 2d', href: '/g/zeepkist-crash-2d/' },
{ title: 'Zomball', href: '/g/zomball/' },
{ title: 'Zombie Apocalypse Shooter', href: '/g/zombie-apocalypse-shooter/' },
{ title: 'Zombie Killer', href: '/g/zombie-killer/' },
{ title: 'Zombie Mission 11', href: '/g/zombie-mission-11/' },
{ title: 'Zombie Outbreak Arena', href: '/g/zombie-outbreak-arena/' },
{ title: 'Zombie Shooter 2d', href: '/g/zombie-shooter-2d/' },
{ title: 'Zombie Siege Outbreak', href: '/g/zombie-siege-outbreak/' },
{ title: 'Zombies Are Coming', href: '/g/zombies-are-coming/' },
{ title: 'Zombies Royale Impostor Drive', href: '/g/zombies-royale-impostor-drive/' },
{ title: 'Zombies Survival', href: '/g/zombies-survival/' },
{ title: 'Zombotag', href: '/g/zombotag/' },
{ title: 'Zombsroyale Io', href: '/g/zombsroyale-io/' },
{ title: 'Zoom Be 3', href: '/g/zoom-be-3/' },
{ title: 'Zuck Vs Musk Techbro Beatdown', href: '/g/zuck-vs-musk-techbro-beatdown/' }
    ].map((item) => ({ ...item, titleLower: item.title.toLowerCase(), img: `/assest/images/${item.href.slice(3, -1)}.webp` }));

    const topGames = games.slice(0, 35);

    const createElement = (tag, className, text) => {
        const el = document.createElement(tag);
        if (className) el.className = className;
        if (text !== undefined) el.textContent = text;
        return el;
    };

    const hideDropdown = () => {
        searchSuggestions.classList.add('hidden');
        searchSuggestions.innerHTML = '';
    };

    const renderDropdown = (query) => {
        const searchValue = query.trim().toLowerCase();
        const matches = searchValue ? games.filter((game) => game.titleLower.includes(searchValue)) : [];
        const items = matches.slice(0, 4);
        searchSuggestions.innerHTML = '';

        if (!searchValue) {
            hideDropdown();
            return;
        }

        if (!items.length) {
            const empty = createElement('div', 'search-dropdown-empty');
            const message = createElement('div', null, `No games found for “${query}”.`);
            const seeAllButton = createElement('button', 'search-dropdown-see-all', 'Show top games');
            seeAllButton.type = 'button';
            seeAllButton.addEventListener('click', () => submitSearch(query));
            empty.appendChild(message);
            empty.appendChild(seeAllButton);
            searchSuggestions.appendChild(empty);
            searchSuggestions.classList.remove('hidden');
            return;
        }

        items.forEach((game) => {
            const item = createElement('div', 'search-dropdown-item');
            const thumb = createElement('img', 'search-dropdown-thumb');
            thumb.src = game.img;
            thumb.alt = game.title;
            thumb.loading = 'lazy';
            const title = createElement('span', null, game.title);
            item.appendChild(thumb);
            item.appendChild(title);
            item.addEventListener('click', () => {
                window.location.href = game.href;
            });
            searchSuggestions.appendChild(item);
        });

        const seeAll = createElement('div', 'search-dropdown-see-all', `See all results for “${query}”`);
        seeAll.addEventListener('click', () => submitSearch(query));
        searchSuggestions.appendChild(seeAll);
        searchSuggestions.classList.remove('hidden');
    };

    const renderResults = (query) => {
        const searchValue = query.trim().toLowerCase();
        const matches = searchValue ? games.filter((game) => game.titleLower.includes(searchValue)) : [];
        const showGames = matches.length ? matches : topGames;

        resultsTitle.textContent = searchValue
            ? matches.length
                ? `Results for “${query}”`
                : `No results for “${query}”`
            : 'Top games';

        resultsNote.textContent = searchValue
            ? matches.length
                ? `Showing ${showGames.length} games that match your search.`
                : 'No direct matches were found, so we are showing our top 35 games instead.'
            : 'Browse our top 35 games.';

        resultsGrid.innerHTML = '';

        showGames.forEach((game) => {
            const card = createElement('a', 'search-result-card');
            card.href = game.href;
            const thumb = createElement('img', 'search-result-card-thumb');
            thumb.src = game.img;
            thumb.alt = game.title;
            const body = createElement('div', 'search-result-card-body', game.title);
            card.appendChild(thumb);
            card.appendChild(body);
            resultsGrid.appendChild(card);
        });
    };

    const hideSearchResults = () => {
        searchResultsPage.classList.remove('active');
        searchInput.value = '';
    };

    const submitSearch = (query) => {
        const trimmed = query.trim();
        if (!trimmed) {
            hideDropdown();
            hideSearchResults();
            return;
        }
        renderResults(trimmed);
        searchResultsPage.classList.add('active');
        hideDropdown();
    };

    resultsClose.addEventListener('click', hideSearchResults);

    searchInput.addEventListener('input', (event) => {
        renderDropdown(event.target.value || '');
    });

    searchInput.addEventListener('keydown', (event) => {
        if (event.key === 'Enter') {
            event.preventDefault();
            submitSearch(searchInput.value);
        }
        if (event.key === 'Escape') {
            hideDropdown();
            hideSearchResults();
        }
    });

    searchForm.addEventListener('submit', (event) => {
        event.preventDefault();
        submitSearch(searchInput.value);
    });

    document.addEventListener('click', (event) => {
        if (!searchForm.contains(event.target) && !searchSuggestions.contains(event.target)) {
            hideDropdown();
        }
    });
})();