(function() {
    const searchInput = document.getElementById('search-input');
    const searchForm = document.querySelector('.search-form');
    const searchSuggestions = document.getElementById('search-suggestions');
    const searchResultsPage = document.getElementById('search-results-page');
    const resultsTitle = document.getElementById('search-results-title');
    const resultsNote = document.getElementById('search-results-note');
    const resultsGrid = document.getElementById('search-results-grid');
    const resultsClose = document.getElementById('search-results-close');
    const mobileSearchButton = document.getElementById('mobile-search-button');
    const mobileSearchPopup = document.getElementById('mobile-search-popup');
    const mobileSearchClose = document.getElementById('mobile-search-close');
    const mobileSearchForm = document.getElementById('mobile-search-form');
    const mobileSearchInput = document.getElementById('mobile-search-input');

    if (!searchInput || !searchForm || !searchSuggestions || !searchResultsPage || !resultsTitle || !resultsNote || !resultsGrid || !resultsClose) {
        return;
    }

    const games = [
{'title':'2048','href':'/g/2048/' },
{'title':'11 11','href':'/g/11-11/' },
{'title':'10 Minutes Till Dawn','href':'/g/10-minutes-till-dawn/' },
{'title':'1010 Color Match','href':'/g/1010-color-match/' },
{'title':'12 Mini Battles 2','href':'/g/12-mini-battles-2/' },
{'title':'12 Minibattles','href':'/g/12-minibattles/' },
{'title':'18 Wheeler Cargo Simulator','href':'/g/18-wheeler-cargo-simulator/' },
{'title':'18 Wheeler Cargo Simulator 2','href':'/g/18-wheeler-cargo-simulator-2/' },
{'title':'18 Wheeler Truck Parking','href':'/g/18-wheeler-truck-parking/' },
{'title':'18 Wheeler Truck Parking 2','href':'/g/18-wheeler-truck-parking-2/' },
{'title':'1v1 Lol','href':'/g/1v1-lol/' },
{'title':'2048 Cupcakes','href':'/g/2048-cupcakes/' },
{'title':'2048 Fusion','href':'/g/2048-fusion/' },
{'title':'3 Pandas In Japan','href':'/g/3-pandas-in-japan/' },
{'title':'3d Arena Racing','href':'/g/3d-arena-racing/' },
{'title':'3d Bowling','href':'/g/3d-bowling/' },
{'title':'3d Car Simulator','href':'/g/3d-car-simulator/' },
{'title':'3d Free Kick','href':'/g/3d-free-kick/' },
{'title':'3d Moto Simulator 2','href':'/g/3d-moto-simulator-2/' },
{'title':'4th And Goal 2022','href':'/g/4th-and-goal-2022/' },
{'title':'4wd Off Road Driving Sim','href':'/g/4wd-off-road-driving-sim/' },
{'title':'4x4 Off Road','href':'/g/4x4-off-road/' },
{'title':'8 Ball Pool','href':'/g/8-ball-pool/' },
{'title':'99 Balls','href':'/g/99-balls/' },
{'title':'99 Nights In The Forest','href':'/g/99-nights-in-the-forest/' },
{'title':'A Dance Of Fire And Ice','href':'/g/a-dance-of-fire-and-ice/' },
{'title':'A Pretty Odd Bunny','href':'/g/a-pretty-odd-bunny/' },
{'title':'A Small World Cup','href':'/g/a-small-world-cup/' },
{'title':'Achievement Unlocked','href':'/g/achievement-unlocked/' },
{'title':'Adam And Eve 5 Part 1','href':'/g/adam-and-eve-5-part-1/' },
{'title':'Adam And Eve 5 Part 2','href':'/g/adam-and-eve-5-part-2/' },
{'title':'Adam And Eve 6','href':'/g/adam-and-eve-6/' },
{'title':'Adam And Eve 7','href':'/g/adam-and-eve-7/' },
{'title':'Adventure Drivers','href':'/g/adventure-drivers/' },
{'title':'Agar Io','href':'/g/agar-io/' },
{'title':'Agarpaper Io','href':'/g/agarpaper-io/' },
{'title':'Air Hockey Championship Deluxe','href':'/g/air-hockey-championship-deluxe/' },
{'title':'Alien Hominid Hd','href':'/g/alien-hominid-hd/' },
{'title':'Amazing Rope Vice Spider Vegas','href':'/g/amazing-rope-vice-spider-vegas/' },
{'title':'Amidst The Sky','href':'/g/amidst-the-sky/' },
{'title':'Among Us','href':'/g/among-us/' },
{'title':'Angry Birds','href':'/g/angry-birds/' },
{'title':'Angry Gran Run','href':'/g/angry-gran-run/' },
{'title':'Apple Shooter','href':'/g/apple-shooter/' },
{'title':'Apple Worm','href':'/g/apple-worm/' },
{'title':'Aquapark Io','href':'/g/aquapark-io/' },
{'title':'Arcane Archer','href':'/g/arcane-archer/' },
{'title':'Archery World Tour','href':'/g/archery-world-tour/' },
{'title':'Arithmetica','href':'/g/arithmetica/' },
{'title':'Arras Io','href':'/g/arras-io/' },
{'title':'Aspiring Artist','href':'/g/aspiring-artist/' },
{'title':'Awesome Tanks 2','href':'/g/awesome-tanks-2/' },
{'title':'Axis Football League','href':'/g/axis-football-league/' },
{'title':'Backflipper','href':'/g/backflipper/' },
{'title':'Backrooms','href':'/g/backrooms/' },
{'title':'Backrooms 2d','href':'/g/backrooms-2d/' },
{'title':'Bacon May Die','href':'/g/bacon-may-die/' },
{'title':'Bad Egg','href':'/g/bad-egg/' },
{'title':'Bad Ice Cream','href':'/g/bad-ice-cream/' },
{'title':'Bad Ice Cream 2','href':'/g/bad-ice-cream-2/' },
{'title':'Bad Ice Cream 3','href':'/g/bad-ice-cream-3/' },
{'title':'Bad Monday Simulator','href':'/g/bad-monday-simulator/' },
{'title':'Baldis Basics','href':'/g/baldis-basics/' },
{'title':'Baldis Basics Field Trip','href':'/g/baldis-basics-field-trip/' },
{'title':'Ball Sort Halloween','href':'/g/ball-sort-halloween/' },
{'title':'Ball Sort Soccer','href':'/g/ball-sort-soccer/' },
{'title':'Ballistic','href':'/g/ballistic/' },
{'title':'Basket And Ball','href':'/g/basket-and-ball/' },
{'title':'Basket Battle','href':'/g/basket-battle/' },
{'title':'Basket Bros Io','href':'/g/basket-bros-io/' },
{'title':'Basket Champs','href':'/g/basket-champs/' },
{'title':'Basket Monsterz','href':'/g/basket-monsterz/' },
{'title':'Basket Random','href':'/g/basket-random/' },
{'title':'Basket Slam Dunk 2','href':'/g/basket-slam-dunk-2/' },
{'title':'Basket Swooshes','href':'/g/basket-swooshes/' },
{'title':'Basket Swooshes Plus','href':'/g/basket-swooshes-plus/' },
{'title':'Basketball Clash','href':'/g/basketball-clash/' },
{'title':'Basketball Frvr','href':'/g/basketball-frvr/' },
{'title':'Basketball Io','href':'/g/basketball-io/' },
{'title':'Basketball King','href':'/g/basketball-king/' },
{'title':'Basketball League','href':'/g/basketball-league/' },
{'title':'Basketball Legends 2020','href':'/g/basketball-legends-2020/' },
{'title':'Basketball Line','href':'/g/basketball-line/' },
{'title':'Basketball Orbit','href':'/g/basketball-orbit/' },
{'title':'Basketball Serial Shooter','href':'/g/basketball-serial-shooter/' },
{'title':'Basketball Skills','href':'/g/basketball-skills/' },
{'title':'Basketball Slam Dunk','href':'/g/basketball-slam-dunk/' },
{'title':'Basketball Stars','href':'/g/basketball-stars/' },
{'title':'Basketball Superstars','href':'/g/basketball-superstars/' },
{'title':'Battle Wheels','href':'/g/battle-wheels/' },
{'title':'Battledudes Io','href':'/g/battledudes-io/' },
{'title':'Bearsus','href':'/g/bearsus/' },
{'title':'Betrayal Io','href':'/g/betrayal-io/' },
{'title':'Bicycle Stunts 3d','href':'/g/bicycle-stunts-3d/' },
{'title':'Big Shot Boxing','href':'/g/big-shot-boxing/' },
{'title':'Big Tower Tiny Square','href':'/g/big-tower-tiny-square/' },
{'title':'Bike Trials Offroad 1','href':'/g/bike-trials-offroad-1/' },
{'title':'Bike Trials Winter 1','href':'/g/bike-trials-winter-1/' },
{'title':'Bike Trials Winter 2','href':'/g/bike-trials-winter-2/' },
{'title':'Bikers Street','href':'/g/bikers-street/' },
{'title':'Bitlife','href':'/g/bitlife/' },
{'title':'Block Blast','href':'/g/block-blast/' },
{'title':'Block World','href':'/g/block-world/' },
{'title':'Blockpost','href':'/g/blockpost/' },
{'title':'Blocky Cars','href':'/g/blocky-cars/' },
{'title':'Blocky Snakes','href':'/g/blocky-snakes/' },
{'title':'Blocky Trials','href':'/g/blocky-trials/' },
{'title':'Bloons Td Battles 2','href':'/g/bloons-td-battles-2/' },
{'title':'Bloons Tower Defense 4','href':'/g/bloons-tower-defense-4/' },
{'title':'Bloxd Io','href':'/g/bloxd-io/' },
{'title':'Bloxorz','href':'/g/bloxorz/' },
{'title':'Blumgi Ball','href':'/g/blumgi-ball/' },
{'title':'Blumgi Bloom','href':'/g/blumgi-bloom/' },
{'title':'Blumgi Castle','href':'/g/blumgi-castle/' },
{'title':'Blumgi Paintball','href':'/g/blumgi-paintball/' },
{'title':'Blumgi Rocket','href':'/g/blumgi-rocket/' },
{'title':'Blumgi Slime','href':'/g/blumgi-slime/' },
{'title':'Blumgi Soccer','href':'/g/blumgi-soccer/' },
{'title':'Bob The Robber 2','href':'/g/bob-the-robber-2/' },
{'title':'Bob The Robber 4','href':'/g/bob-the-robber-4/' },
{'title':'Bomb It 7','href':'/g/bomb-it-7/' },
{'title':'Booblehead Soccer Royale','href':'/g/booblehead-soccer-royale/' },
{'title':'Bottle Flip 3d','href':'/g/bottle-flip-3d/' },
{'title':'Bouncy Woods','href':'/g/bouncy-woods/' },
{'title':'Bowling Stars','href':'/g/bowling-stars/' },
{'title':'Boxing Physics 2','href':'/g/boxing-physics-2/' },
{'title':'Boxing Random','href':'/g/boxing-random/' },
{'title':'Boxing Stars','href':'/g/boxing-stars/' },
{'title':'Braains Io','href':'/g/braains-io/' },
{'title':'Brain For Monster Truck','href':'/g/brain-for-monster-truck/' },
{'title':'Brain Test 2 Tricky Stories','href':'/g/brain-test-2-tricky-stories/' },
{'title':'Brain Test 3 Tricky Quests','href':'/g/brain-test-3-tricky-quests/' },
{'title':'Brain Test Tricky Puzzles','href':'/g/brain-test-tricky-puzzles/' },
{'title':'Breaking The Bank','href':'/g/breaking-the-bank/' },
{'title':'Bubble Pop Adventures','href':'/g/bubble-pop-adventures/' },
{'title':'Bubble Shooter','href':'/g/bubble-shooter/' },
{'title':'Bubble Trouble','href':'/g/bubble-trouble/' },
{'title':'Bubble Trouble 3','href':'/g/bubble-trouble-3/' },
{'title':'Build Crush','href':'/g/build-crush/' },
{'title':'Bullet Force','href':'/g/bullet-force/' },
{'title':'Bullet Party 2','href':'/g/bullet-party-2/' },
{'title':'Bumper Cars Soccer','href':'/g/bumper-cars-soccer/' },
{'title':'Bunny Hop','href':'/g/bunny-hop/' },
{'title':'Burger Clicker','href':'/g/burger-clicker/' },
{'title':'Burrito Bison ','href':'/g/burrito-bison-/' },
{'title':'Candy Crush Saga','href':'/g/candy-crush-saga/' },
{'title':'Cannon Basketball 4','href':'/g/cannon-basketball-4/' },
{'title':'Car Rush','href':'/g/car-rush/' },
{'title':'Car Simulator 2','href':'/g/car-simulator-2/' },
{'title':'Case Clicker','href':'/g/case-clicker/' },
{'title':'Cat Gunner ','href':'/g/cat-gunner-/' },
{'title':'Checkers','href':'/g/checkers/' },
{'title':'Chicken Merge','href':'/g/chicken-merge/' },
{'title':'Choppy Orc','href':'/g/choppy-orc/' },
{'title':'Chrome Dino','href':'/g/chrome-dino/' },
{'title':'Circlo0','href':'/g/circlo0/' },
{'title':'City Coach Bus Simulator 3d','href':'/g/city-coach-bus-simulator-3d/' },
{'title':'Clicker Heroes','href':'/g/clicker-heroes/' },
{'title':'Climb Over It','href':'/g/climb-over-it/' },
{'title':'Connect 3','href':'/g/connect-3/' },
{'title':'Cookie Clicker','href':'/g/cookie-clicker/' },
{'title':'Craftmine','href':'/g/craftmine/' },
{'title':'Crazy Cars','href':'/g/crazy-cars/' },
{'title':'Crazy Tunnel 3d','href':'/g/crazy-tunnel-3d/' },
{'title':'Creative Kill Chamber','href':'/g/creative-kill-chamber/' },
{'title':'Cricket World Cup','href':'/g/cricket-world-cup/' },
{'title':'Crossy Road','href':'/g/crossy-road/' },
{'title':'Cubeshot Io','href':'/g/cubeshot-io/' },
{'title':'Cut The Rope','href':'/g/cut-the-rope/' },
{'title':'Dark Ninja','href':'/g/dark-ninja/' },
{'title':'Dashcraft Io','href':'/g/dashcraft-io/' },
{'title':'Dead Again','href':'/g/dead-again/' },
{'title':'Deadshot Io','href':'/g/deadshot-io/' },
{'title':'Deal Or No Deal','href':'/g/deal-or-no-deal/' },
{'title':'Death Run 3d','href':'/g/death-run-3d/' },
{'title':'Deathcar Io','href':'/g/deathcar-io/' },
{'title':'Diebrary','href':'/g/diebrary/' },
{'title':'Dinosaur Game','href':'/g/dinosaur-game/' },
{'title':'Dinosaurs Merge Master','href':'/g/dinosaurs-merge-master/' },
{'title':'Doge Miner','href':'/g/doge-miner/' },
{'title':'Doodle Jump','href':'/g/doodle-jump/' },
{'title':'Dots And Boxes','href':'/g/dots-and-boxes/' },
{'title':'Down The Hill','href':'/g/down-the-hill/' },
{'title':'Dreadhead Parkour','href':'/g/dreadhead-parkour/' },
{'title':'Drift Boss','href':'/g/drift-boss/' },
{'title':'Drift Hunters','href':'/g/drift-hunters/' },
{'title':'Drive Mad','href':'/g/drive-mad/' },
{'title':'Drop Kick World Cup','href':'/g/drop-kick-world-cup/' },
{'title':'Duke Dashington Remastered','href':'/g/duke-dashington-remastered/' },
{'title':'Dunkers','href':'/g/dunkers/' },
{'title':'Dunkers 2','href':'/g/dunkers-2/' },
{'title':'Duck Life','href':'/g/duck-life/' },
{'title':'Duck Life 2','href':'/g/duck-life-2/' },
{'title':'Duck Life 3','href':'/g/duck-life-3/' },
{'title':'Duck Life 4','href':'/g/duck-life-4/' },
{'title':'Duck Life 5','href':'/g/duck-life-5/' },
{'title':'Eggy Car','href':'/g/eggy-car/' },
{'title':'Elastic Man','href':'/g/elastic-man/' },
{'title':'Electron Dash','href':'/g/electron-dash/' },
{'title':'Endless Tunnel','href':'/g/endless-tunnel/' },
{'title':'Endless War 3','href':'/g/endless-war-3/' },
{'title':'Escape Road','href':'/g/escape-road/' },
{'title':'Escape Road 2','href':'/g/escape-road-2/' },
{'title':'Ev Io','href':'/g/ev-io/' },
{'title':'Extreme Run 3d','href':'/g/extreme-run-3d/' },
{'title':'Fallguys','href':'/g/fallguys/' },
{'title':'Farm Match Seasons','href':'/g/farm-match-seasons/' },
{'title':'Ferge Io','href':'/g/ferge-io/' },
{'title':'Fightz Io','href':'/g/fightz-io/' },
{'title':'Fire Truck Rescue','href':'/g/fire-truck-rescue/' },
{'title':'Fireboy And Watergirl 2','href':'/g/fireboy-and-watergirl-2/' },
{'title':'Fireboy And Watergirl 3','href':'/g/fireboy-and-watergirl-3/' },
{'title':'Fireboy And Watergirl 4','href':'/g/fireboy-and-watergirl-4/' },
{'title':'Fireboy And Watergirl 5 Elements','href':'/g/fireboy-and-watergirl-5-elements/' },
{'title':'Fireboy And Watergirl 6','href':'/g/fireboy-and-watergirl-6/' },
{'title':'Fireboy And Watergirl Forest Temple','href':'/g/fireboy-and-watergirl-forest-temple/' },
{'title':'Fishing And Lines','href':'/g/fishing-and-lines/' },
{'title':'Fishing Frenzy','href':'/g/fishing-frenzy/' },
{'title':'Five Nights At Freddys 2','href':'/g/five-nights-at-freddys-2/' },
{'title':'Five Nights At Freddys 3','href':'/g/five-nights-at-freddys-3/' },
{'title':'Five Nights At Freddys 4','href':'/g/five-nights-at-freddys-4/' },
{'title':'Flappy Bird','href':'/g/flappy-bird/' },
{'title':'Flappy Dunk','href':'/g/flappy-dunk/' },
{'title':'Fnaf Shooter','href':'/g/fnaf-shooter/' },
{'title':'Football Legends','href':'/g/football-legends/' },
{'title':'Football Masters','href':'/g/football-masters/' },
{'title':'Football Run','href':'/g/football-run/' },
{'title':'Football Strike','href':'/g/football-strike/' },
{'title':'Fortnite Made In China','href':'/g/fortnite-made-in-china/' },
{'title':'Four Color','href':'/g/four-color/' },
{'title':'Free Kick Classic','href':'/g/free-kick-classic/' },
{'title':'Free Kick Shooter','href':'/g/free-kick-shooter/' },
{'title':'Friday Night Funkin','href':'/g/friday-night-funkin/' },
{'title':'Fruit Ninja','href':'/g/fruit-ninja/' },
{'title':'Funny Shooter','href':'/g/funny-shooter/' },
{'title':'Funny Shooter 2','href':'/g/funny-shooter-2/' },
{'title':'G Switch','href':'/g/g-switch/' },
{'title':'G Switch 2','href':'/g/g-switch-2/' },
{'title':'G Switch 3','href':'/g/g-switch-3/' },
{'title':'G Switch 4','href':'/g/g-switch-4/' },
{'title':'Gartic Io','href':'/g/gartic-io/' },
{'title':'Gartic Phone','href':'/g/gartic-phone/' },
{'title':'Geometry Dash','href':'/g/geometry-dash/' },
{'title':'Geometry Dash 2','href':'/g/geometry-dash-2/' },
{'title':'Get On Top','href':'/g/get-on-top/' },
{'title':'Getaway Shootout','href':'/g/getaway-shootout/' },
{'title':'Getting Over It','href':'/g/getting-over-it/' },
{'title':'Gigga Io','href':'/g/gigga-io/' },
{'title':'Goalkeeper Challenge','href':'/g/goalkeeper-challenge/' },
{'title':'Gobdun','href':'/g/gobdun/' },
{'title':'Gold Digger Frvr','href':'/g/gold-digger-frvr/' },
{'title':'Golf Orbit','href':'/g/golf-orbit/' },
{'title':'Grand Prix Hero','href':'/g/grand-prix-hero/' },
{'title':'Grand Vegas Simulator','href':'/g/grand-vegas-simulator/' },
{'title':'Granny','href':'/g/granny/' },
{'title':'Gravity Soccer','href':'/g/gravity-soccer/' },
{'title':'Grindcraft Remastered','href':'/g/grindcraft-remastered/' },
{'title':'Gully Cricket','href':'/g/gully-cricket/' },
{'title':'Gulper Io','href':'/g/gulper-io/' },
{'title':'Gun Mayhem 2','href':'/g/gun-mayhem-2/' },
{'title':'Gun Mayhem Redux','href':'/g/gun-mayhem-redux/' },
{'title':'Gunmayhem','href':'/g/gunmayhem/' },
{'title':'Gun Spin','href':'/g/gun-spin/' },
{'title':'Hammer 2','href':'/g/hammer-2/' },
{'title':'Hanger','href':'/g/hanger/' },
{'title':'Hanger 2','href':'/g/hanger-2/' },
{'title':'Happy Fishing','href':'/g/happy-fishing/' },
{'title':'Happy Wheels','href':'/g/happy-wheels/' },
{'title':'Head Soccer 2022','href':'/g/head-soccer-2022/' },
{'title':'Head Soccer 2023','href':'/g/head-soccer-2023/' },
{'title':'Heads Arena Soccer All Stars','href':'/g/heads-arena-soccer-all-stars/' },
{'title':'Hexanaut Io','href':'/g/hexanaut-io/' },
{'title':'Hill Climb Racing 2','href':'/g/hill-climb-racing-2/' },
{'title':'Hole Io','href':'/g/hole-io/' },
{'title':'Hoop World 3d','href':'/g/hoop-world-3d/' },
{'title':'Hop & Pop It','href':'/g/hop-&-pop-it/' },
{'title':'House Of Hazards','href':'/g/house-of-hazards/' },
{'title':'Icy Purple Head 2','href':'/g/icy-purple-head-2/' },
{'title':'Idle Breakout','href':'/g/idle-breakout/' },
{'title':'Idle Football Manager','href':'/g/idle-football-manager/' },
{'title':'Idle Light City','href':'/g/idle-light-city/' },
{'title':'Idle Mining Empire','href':'/g/idle-mining-empire/' },
{'title':'Idle Tree City','href':'/g/idle-tree-city/' },
{'title':'Impossible Monster Truck','href':'/g/impossible-monster-truck/' },
{'title':'Impossible Tic Tac Toe','href':'/g/impossible-tic-tac-toe/' },
{'title':'Indian Truck Simulator 3d','href':'/g/indian-truck-simulator-3d/' },
{'title':'Infinite Soccer','href':'/g/infinite-soccer/' },
{'title':'Iron Snout','href':'/g/iron-snout/' },
{'title':'Jacksmith','href':'/g/jacksmith/' },
{'title':'Jelly Truck','href':'/g/jelly-truck/' },
{'title':'Jetpack Joyride','href':'/g/jetpack-joyride/' },
{'title':'Jewels Blitz 5','href':'/g/jewels-blitz-5/' },
{'title':'Johnny Trigger','href':'/g/johnny-trigger/' },
{'title':'Johnny Upgrade','href':'/g/johnny-upgrade/' },
{'title':'Jollyworld','href':'/g/jollyworld/' },
{'title':'Jungle Td','href':'/g/jungle-td/' },
{'title':'Just Fall Lol','href':'/g/just-fall-lol/' },
{'title':'Kart Fight Io','href':'/g/kart-fight-io/' },
{'title':'Kart Race 3d','href':'/g/kart-race-3d/' },
{'title':'Kawaii Dressup','href':'/g/kawaii-dressup/' },
{'title':'Kirka Io','href':'/g/kirka-io/' },
{'title':'Knight Hero Adventure Idle Rpg','href':'/g/knight-hero-adventure-idle-rpg/' },
{'title':'Kour Io','href':'/g/kour-io/' },
{'title':'Krunker Io','href':'/g/krunker-io/' },
{'title':'Leader Strike','href':'/g/leader-strike/' },
{'title':'Learn To Fly','href':'/g/learn-to-fly/' },
{'title':'Learntofly2','href':'/g/learntofly2/' },
{'title':'Level Devil','href':'/g/level-devil/' },
{'title':'Little Master Cricket','href':'/g/little-master-cricket/' },
{'title':'Lolbeans Io','href':'/g/lolbeans-io/' },
{'title':'Lolshot Io','href':'/g/lolshot-io/' },
{'title':'Ludo Multiplayer','href':'/g/ludo-multiplayer/' },
{'title':'Lurkers Io','href':'/g/lurkers-io/' },
{'title':'Mad Day','href':'/g/mad-day/' },
{'title':'Mad Gunz','href':'/g/mad-gunz/' },
{'title':'Mad Shark','href':'/g/mad-shark/' },
{'title':'Mad Truck Challenge','href':'/g/mad-truck-challenge/' },
{'title':'Madalin Cars Multiplayer','href':'/g/madalin-cars-multiplayer/' },
{'title':'Madalin Stunt Cars 2','href':'/g/madalin-stunt-cars-2/' },
{'title':'Madalin Stunt Cars 3','href':'/g/madalin-stunt-cars-3/' },
{'title':'Marble Dash','href':'/g/marble-dash/' },
{'title':'Marbles Sorting','href':'/g/marbles-sorting/' },
{'title':'Masked Forces','href':'/g/masked-forces/' },
{'title':'Master Checkers','href':'/g/master-checkers/' },
{'title':'Master Chess','href':'/g/master-chess/' },
{'title':'Maze Path Of Light','href':'/g/maze-path-of-light/' },
{'title':'Maze Planet 3d','href':'/g/maze-planet-3d/' },
{'title':'Merc Zone','href':'/g/merc-zone/' },
{'title':'Merge Cakes','href':'/g/merge-cakes/' },
{'title':'Merge Cyber Racers','href':'/g/merge-cyber-racers/' },
{'title':'Merge Harvest','href':'/g/merge-harvest/' },
{'title':'Merge Master','href':'/g/merge-master/' },
{'title':'Merge Party','href':'/g/merge-party/' },
{'title':'Merge Round Racers','href':'/g/merge-round-racers/' },
{'title':'Minecraft Builder','href':'/g/minecraft-builder/' },
{'title':'Minecraft Case Simulator','href':'/g/minecraft-case-simulator/' },
{'title':'Minecraft Classic','href':'/g/minecraft-classic/' },
{'title':'Minesweeper','href':'/g/minesweeper/' },
{'title':'Minibattles','href':'/g/minibattles/' },
{'title':'Mob City','href':'/g/mob-city/' },
{'title':'Money Movers','href':'/g/money-movers/' },
{'title':'Money Movers 2','href':'/g/money-movers-2/' },
{'title':'Money Movers 3','href':'/g/money-movers-3/' },
{'title':'Money Roller','href':'/g/money-roller/' },
{'title':'Money Rush','href':'/g/money-rush/' },
{'title':'Monkey Mart','href':'/g/monkey-mart/' },
{'title':'Monster Tracks','href':'/g/monster-tracks/' },
{'title':'Monster Truck Arena','href':'/g/monster-truck-arena/' },
{'title':'Monster Truck Vs Zombie','href':'/g/monster-truck-vs-zombie/' },
{'title':'Monsters Wheels Special','href':'/g/monsters-wheels-special/' },
{'title':'Moomoo Io Sandbox','href':'/g/moomoo-io-sandbox/' },
{'title':'Mosaic Puzzle Art','href':'/g/mosaic-puzzle-art/' },
{'title':'Moto Maniac','href':'/g/moto-maniac/' },
{'title':'Moto Maniac 2','href':'/g/moto-maniac-2/' },
{'title':'Moto Maniac 3','href':'/g/moto-maniac-3/' },
{'title':'Moto Trial Racing 2','href':'/g/moto-trial-racing-2/' },
{'title':'Moto X3m','href':'/g/moto-x3m/' },
{'title':'Moto X3m 2','href':'/g/moto-x3m-2/' },
{'title':'Moto X3m 4 Winter','href':'/g/moto-x3m-4-winter/' },
{'title':'Moto X3m 5 Pool Party','href':'/g/moto-x3m-5-pool-party/' },
{'title':'Moto X3m 6 Spooky Land','href':'/g/moto-x3m-6-spooky-land/' },
{'title':'Moto X3m Pool Party','href':'/g/moto-x3m-pool-party/' },
{'title':'Mr Bullet','href':'/g/mr-bullet/' },
{'title':'Mutazone','href':'/g/mutazone/' },
{'title':'My Perfect Hotel','href':'/g/my-perfect-hotel/' },
{'title':'My Pony My Little Race','href':'/g/my-pony-my-little-race/' },
{'title':'Neon War','href':'/g/neon-war/' },
{'title':'Ninja Cat Exploit','href':'/g/ninja-cat-exploit/' },
{'title':'Noob Steve Parkour','href':'/g/noob-steve-parkour/' },
{'title':'Off Road Rain Cargo Simulator','href':'/g/off-road-rain-cargo-simulator/' },
{'title':'Only 3d Parkour','href':'/g/only-3d-parkour/' },
{'title':'Only Up','href':'/g/only-up/' },
{'title':'Only Up 2','href':'/g/only-up-2/' },
{'title':'Orbital Survival','href':'/g/orbital-survival/' },
{'title':'Ovo','href':'/g/ovo/' },
{'title':'Ovo 3 Dimensions','href':'/g/ovo-3-dimensions/' },
{'title':'Ovo Classic','href':'/g/ovo-classic/' },
{'title':'Ovo 2','href':'/g/ovo-2/' },
{'title':'Pac Man World','href':'/g/pac-man-world/' },
{'title':'Pack A Bag','href':'/g/pack-a-bag/' },
{'title':'Pacman','href':'/g/pacman/' },
{'title':'Panda Bubble Shooter','href':'/g/panda-bubble-shooter/' },
{'title':'Panda Simulator 3d','href':'/g/panda-simulator-3d/' },
{'title':'Papa Louie','href':'/g/papa-louie/' },
{'title':'Papa Louie 2','href':'/g/papa-louie-2/' },
{'title':'Papa Louie 3','href':'/g/papa-louie-3/' },
{'title':'Papas Bakeria','href':'/g/papas-bakeria/' },
{'title':'Papas Burgeria','href':'/g/papas-burgeria/' },
{'title':'Papas Cheeseria','href':'/g/papas-cheeseria/' },
{'title':'Papas Donuteria','href':'/g/papas-donuteria/' },
{'title':'Papas Freezeria','href':'/g/papas-freezeria/' },
{'title':'Papas Hot Doggeria','href':'/g/papas-hot-doggeria/' },
{'title':'Papas Pastaria','href':'/g/papas-pastaria/' },
{'title':'Papas Pizzaria','href':'/g/papas-pizzaria/' },
{'title':'Papas Scooperia','href':'/g/papas-scooperia/' },
{'title':'Papas Sushiria','href':'/g/papas-sushiria/' },
{'title':'Papas Taco Mia','href':'/g/papas-taco-mia/' },
{'title':'Papas Wingeria','href':'/g/papas-wingeria/' },
{'title':'Paper Fighter 3d','href':'/g/paper-fighter-3d/' },
{'title':'Paper Io','href':'/g/paper-io/' },
{'title':'Paper Io 2','href':'/g/paper-io-2/' },
{'title':'Paper Io 3','href':'/g/paper-io-3/' },
{'title':'Paper Minecraft','href':'/g/paper-minecraft/' },
{'title':'Park Out','href':'/g/park-out/' },
{'title':'Parking Fury','href':'/g/parking-fury/' },
{'title':'Parking Fury 2','href':'/g/parking-fury-2/' },
{'title':'Parking Fury 3d','href':'/g/parking-fury-3d/' },
{'title':'Parking Fury 3d Bounty Hunter','href':'/g/parking-fury-3d-bounty-hunter/' },
{'title':'Parking Fury 3d Night Thief','href':'/g/parking-fury-3d-night-thief/' },
{'title':'Parking Mania','href':'/g/parking-mania/' },
{'title':'Parkour Race','href':'/g/parkour-race/' },
{'title':'Penalty Fever','href':'/g/penalty-fever/' },
{'title':'Penalty Kicks','href':'/g/penalty-kicks/' },
{'title':'Penalty Shooters','href':'/g/penalty-shooters/' },
{'title':'Penalty Shooters 2','href':'/g/penalty-shooters-2/' },
{'title':'Penalty Shooters 3','href':'/g/penalty-shooters-3/' },
{'title':'Peppa Pig Basketball','href':'/g/peppa-pig-basketball/' },
{'title':'Petz Lol','href':'/g/petz-lol/' },
{'title':'Ping Pong Chaos','href':'/g/ping-pong-chaos/' },
{'title':'Ping Pong Go','href':'/g/ping-pong-go/' },
{'title':'Pixel Gun 3d','href':'/g/pixel-gun-3d/' },
{'title':'Pixel Gun Apocalypse 2','href':'/g/pixel-gun-apocalypse-2/' },
{'title':'Pixel Gun Survival','href':'/g/pixel-gun-survival/' },
{'title':'Pixel Smash Duel','href':'/g/pixel-smash-duel/' },
{'title':'Pizza Tower','href':'/g/pizza-tower/' },
{'title':'Plants Vs Zombies','href':'/g/plants-vs-zombies/' },
{'title':'Pool Club','href':'/g/pool-club/' },
{'title':'Poop Clicker 3','href':'/g/poop-clicker-3/' },
{'title':'Poor Bunny','href':'/g/poor-bunny/' },
{'title':'Pop It Master','href':'/g/pop-it-master/' },
{'title':'Pou','href':'/g/pou/' },
{'title':'President Simulator','href':'/g/president-simulator/' },
{'title':'Pudding Monsters','href':'/g/pudding-monsters/' },
{'title':'Push The Box','href':'/g/push-the-box/' },
{'title':'Push The Box 3d','href':'/g/push-the-box-3d/' },
{'title':'Rabbit Samurai','href':'/g/rabbit-samurai/' },
{'title':'Rabbit Samurai 2','href':'/g/rabbit-samurai-2/' },
{'title':'Raft Wars','href':'/g/raft-wars/' },
{'title':'Raft Wars 2','href':'/g/raft-wars-2/' },
{'title':'Ragdoll Fight','href':'/g/ragdoll-fight/' },
{'title':'Ragdoll Hit','href':'/g/ragdoll-hit/' },
{'title':'Rainbow Parkour','href':'/g/rainbow-parkour/' },
{'title':'Rally Champion','href':'/g/rally-champion/' },
{'title':'Rally Point 3','href':'/g/rally-point-3/' },
{'title':'Real Flying Truck Simulator 3d','href':'/g/real-flying-truck-simulator-3d/' },
{'title':'Real Football','href':'/g/real-football/' },
{'title':'Real Garbage Truck','href':'/g/real-garbage-truck/' },
{'title':'Recoil','href':'/g/recoil/' },
{'title':'Red Ball 4','href':'/g/red-ball-4/' },
{'title':'Red Driver 5','href':'/g/red-driver-5/' },
{'title':'Repuls Io','href':'/g/repuls-io/' },
{'title':'Retro Bowl','href':'/g/retro-bowl/' },
{'title':'Retro Bowl College','href':'/g/retro-bowl-college/' },
{'title':'Retro Bowl College','href':'/g/retro-bowl-college/' },
{'title':'Return Man 2','href':'/g/return-man-2/' },
{'title':'Riddle School 5','href':'/g/riddle-school-5/' },
{'title':'Riddle Transfer 2','href':'/g/riddle-transfer-2/' },
{'title':'Rise Of Neon Square','href':'/g/rise-of-neon-square/' },
{'title':'Roblox','href':'/g/roblox/' },
{'title':'Rocket League','href':'/g/rocket-league/' },
{'title':'Rocket Pult','href':'/g/rocket-pult/' },
{'title':'Rocket Soccer Derby','href':'/g/rocket-soccer-derby/' },
{'title':'Rogue Dunk','href':'/g/rogue-dunk/' },
{'title':'Rolling Ball 3d','href':'/g/rolling-ball-3d/' },
{'title':'Rolly Vortex','href':'/g/rolly-vortex/' },
{'title':'Rolly Vortex Ball','href':'/g/rolly-vortex-ball/' },
{'title':'Rooftop Snipers','href':'/g/rooftop-snipers/' },
{'title':'Rooftop Snipers','href':'/g/rooftop-snipers/' },
{'title':'Rooftop Snipers 2','href':'/g/rooftop-snipers-2/' },
{'title':'Rowdy Wrestling','href':'/g/rowdy-wrestling/' },
{'title':'Royale Dudes','href':'/g/royale-dudes/' },
{'title':'Run 3 Editor','href':'/g/run-3-editor/' },
{'title':'Run 3d','href':'/g/run-3d/' },
{'title':'Running Fred','href':'/g/running-fred/' },
{'title':'Rusher Crusher','href':'/g/rusher-crusher/' },
{'title':'Sandstrike Io','href':'/g/sandstrike-io/' },
{'title':'Sausage Flip','href':'/g/sausage-flip/' },
{'title':'Save The Doge','href':'/g/save-the-doge/' },
{'title':'Scenexe Io','href':'/g/scenexe-io/' },
{'title':'Scrap Metal 3 Infernal Trap','href':'/g/scrap-metal-3-infernal-trap/' },
{'title':'Shady Bears','href':'/g/shady-bears/' },
{'title':'Shape Fold','href':'/g/shape-fold/' },
{'title':'Shape Fold Animals','href':'/g/shape-fold-animals/' },
{'title':'Shark Io','href':'/g/shark-io/' },
{'title':'Shell Shockers','href':'/g/shell-shockers/' },
{'title':'Ships 3d','href':'/g/ships-3d/' },
{'title':'Shootz','href':'/g/shootz/' },
{'title':'Short Ride','href':'/g/short-ride/' },
{'title':'Simplyup Io','href':'/g/simplyup-io/' },
{'title':'Sink It','href':'/g/sink-it/' },
{'title':'Skibidi Shooter','href':'/g/skibidi-shooter/' },
{'title':'Skibidi Toilet Rampage','href':'/g/skibidi-toilet-rampage/' },
{'title':'Skiing Fred','href':'/g/skiing-fred/' },
{'title':'Skillfite Io','href':'/g/skillfite-io/' },
{'title':'Slime Road','href':'/g/slime-road/' },
{'title':'Slime Rush Td','href':'/g/slime-rush-td/' },
{'title':'Slope','href':'/g/slope/' },
{'title':'Slope 2','href':'/g/slope-2/' },
{'title':'Slope 3','href':'/g/slope-3/' },
{'title':'Slope City','href':'/g/slope-city/' },
{'title':'Slope Tunnel','href':'/g/slope-tunnel/' },
{'title':'Slopey','href':'/g/slopey/' },
{'title':'Smash Karts','href':'/g/smash-karts/' },
{'title':'Snail Bob 5 Love Story','href':'/g/snail-bob-5-love-story/' },
{'title':'Snail Bob 6 Winter Story','href':'/g/snail-bob-6-winter-story/' },
{'title':'Snail Bob 7 Fantasy Story','href':'/g/snail-bob-7-fantasy-story/' },
{'title':'Snail Bob 8 Island Story','href':'/g/snail-bob-8-island-story/' },
{'title':'Snake','href':'/g/snake/' },
{'title':'Snake Clash','href':'/g/snake-clash/' },
{'title':'Snake Io','href':'/g/snake-io/' },
{'title':'Snay Io','href':'/g/snay-io/' },
{'title':'Sniper 3d','href':'/g/sniper-3d/' },
{'title':'Sniper Shot Bullet Time','href':'/g/sniper-shot-bullet-time/' },
{'title':'Snipey Io','href':'/g/snipey-io/' },
{'title':'Snow Rider 3d','href':'/g/snow-rider-3d/' },
{'title':'Snowball Io','href':'/g/snowball-io/' },
{'title':'Soccer Bros','href':'/g/soccer-bros/' },
{'title':'Soccer Dash','href':'/g/soccer-dash/' },
{'title':'Soccer Heads','href':'/g/soccer-heads/' },
{'title':'Soccer Legends 2021','href':'/g/soccer-legends-2021/' },
{'title':'Soccer Random','href':'/g/soccer-random/' },
{'title':'Soccer Skills Champions League','href':'/g/soccer-skills-champions-league/' },
{'title':'Soccer Skills Euro Cup','href':'/g/soccer-skills-euro-cup/' },
{'title':'Soccer Skills World Cup','href':'/g/soccer-skills-world-cup/' },
{'title':'Sonic The Hedgehog Remastere','href':'/g/sonic-the-hedgehog-remastere/' },
{'title':'Space Is Key','href':'/g/space-is-key/' },
{'title':'Spider Solitaire','href':'/g/spider-solitaire/' },
{'title':'Sprinter','href':'/g/sprinter/' },
{'title':'Stabfish 2','href':'/g/stabfish-2/' },
{'title':'Stabfish Io','href':'/g/stabfish-io/' },
{'title':'Stack Bump 3d','href':'/g/stack-bump-3d/' },
{'title':'Stair Race 3d','href':'/g/stair-race-3d/' },
{'title':'Starblast','href':'/g/starblast/' },
{'title':'Stealing The Diamond','href':'/g/stealing-the-diamond/' },
{'title':'Stick Archers Battle','href':'/g/stick-archers-battle/' },
{'title':'Stick Defenders','href':'/g/stick-defenders/' },
{'title':'Stick Duel Battle','href':'/g/stick-duel-battle/' },
{'title':'Stick Merge','href':'/g/stick-merge/' },
{'title':'Stickbattle Lo','href':'/g/stickbattle-lo/' },
{'title':'Stickman Army The Resistance','href':'/g/stickman-army-the-resistance/' },
{'title':'Stickman Boost','href':'/g/stickman-boost/' },
{'title':'Stickman Boost 2','href':'/g/stickman-boost-2/' },
{'title':'Stickman Fighter Mega Brawl','href':'/g/stickman-fighter-mega-brawl/' },
{'title':'Stickman Golf','href':'/g/stickman-golf/' },
{'title':'Stickman Hook','href':'/g/stickman-hook/' },
{'title':'Stickman Ragdoll Crash Fun','href':'/g/stickman-ragdoll-crash-fun/' },
{'title':'Stickman Vs Zombies','href':'/g/stickman-vs-zombies/' },
{'title':'Stickman Warriors','href':'/g/stickman-warriors/' },
{'title':'Stock Car Hero','href':'/g/stock-car-hero/' },
{'title':'Street Ball Jam','href':'/g/street-ball-jam/' },
{'title':'Stupid Zombies 2','href':'/g/stupid-zombies-2/' },
{'title':'Subway Princess Runner','href':'/g/subway-princess-runner/' },
{'title':'Subway Surfers','href':'/g/subway-surfers/' },
{'title':'Subway Surfers Bali','href':'/g/subway-surfers-bali/' },
{'title':'Subway Surfers Hawaii','href':'/g/subway-surfers-hawaii/' },
{'title':'Subway Surfers New York','href':'/g/subway-surfers-new-york/' },
{'title':'Subway Surfers San Francisco','href':'/g/subway-surfers-san-francisco/' },
{'title':'Subway Surfers Zurich','href':'/g/subway-surfers-zurich/' },
{'title':'Sugar Shock','href':'/g/sugar-shock/' },
{'title':'Suika Game','href':'/g/suika-game/' },
{'title':'Super Bike The Champion','href':'/g/super-bike-the-champion/' },
{'title':'Super Falling Fred','href':'/g/super-falling-fred/' },
{'title':'Super Fowlst','href':'/g/super-fowlst/' },
{'title':'Super Hexbee Merger','href':'/g/super-hexbee-merger/' },
{'title':'Super Liquid Soccer','href':'/g/super-liquid-soccer/' },
{'title':'Super Mario 64','href':'/g/super-mario-64/' },
{'title':'Super Mario Bros','href':'/g/super-mario-bros/' },
{'title':'Super Mx The Champion','href':'/g/super-mx-the-champion/' },
{'title':'Super Onion Boy','href':'/g/super-onion-boy/' },
{'title':'Super Santa Kicker','href':'/g/super-santa-kicker/' },
{'title':'Super Tunnel Rush','href':'/g/super-tunnel-rush/' },
{'title':'Superbattle 2','href':'/g/superbattle-2/' },
{'title':'Superbike Hero','href':'/g/superbike-hero/' },
{'title':'Super Hot','href':'/g/super-hot/' },
{'title':'Surviv Io','href':'/g/surviv-io/' },
{'title':'Survivor In Rainbow Monster','href':'/g/survivor-in-rainbow-monster/' },
{'title':'Table Tennis Ultimate Tournament','href':'/g/table-tennis-ultimate-tournament/' },
{'title':'Table Tennis World Tour','href':'/g/table-tennis-world-tour/' },
{'title':'Tag 2','href':'/g/tag-2/' },
{'title':'Taming Io','href':'/g/taming-io/' },
{'title':'Tank Trouble','href':'/g/tank-trouble/' },
{'title':'Tank Trouble 2','href':'/g/tank-trouble-2/' },
{'title':'Tanuki Sunset','href':'/g/tanuki-sunset/' },
{'title':'Tap Tap Shots','href':'/g/tap-tap-shots/' },
{'title':'Temple Run 2','href':'/g/temple-run-2/' },
{'title':'Tennis Masters','href':'/g/tennis-masters/' },
{'title':'Tetra Blocks','href':'/g/tetra-blocks/' },
{'title':'Tetris','href':'/g/tetris/' },
{'title':'Tetris 99','href':'/g/tetris-99/' },
{'title':'The Backrooms','href':'/g/the-backrooms/' },
{'title':'The Bowling Club','href':'/g/the-bowling-club/' },
{'title':'The Final Earth','href':'/g/the-final-earth/' },
{'title':'The Final Earth 2','href':'/g/the-final-earth-2/' },
{'title':'The Fish Master','href':'/g/the-fish-master/' },
{'title':'The Heist','href':'/g/the-heist/' },
{'title':'The Impossible Quiz','href':'/g/the-impossible-quiz/' },
{'title':'The Impossible Quiz 2','href':'/g/the-impossible-quiz-2/' },
{'title':'The Little Giant','href':'/g/the-little-giant/' },
{'title':'The Spear Stickman','href':'/g/the-spear-stickman/' },
{'title':'The Worlds Hardest Game','href':'/g/the-worlds-hardest-game/' },
{'title':'The Worlds Hardest Game 3','href':'/g/the-worlds-hardest-game-3/' },
{'title':'There Is No Game','href':'/g/there-is-no-game/' },
{'title':'Thumb Fighter','href':'/g/thumb-fighter/' },
{'title':'Tic Tac Toe','href':'/g/tic-tac-toe/' },
{'title':'Timber Man','href':'/g/timber-man/' },
{'title':'Time Shooter 2','href':'/g/time-shooter-2/' },
{'title':'Time Shooter 3','href':'/g/time-shooter-3/' },
{'title':'Tiny Fishing','href':'/g/tiny-fishing/' },
{'title':'Tiny Town Racing','href':'/g/tiny-town-racing/' },
{'title':'Tomb Of The Mask','href':'/g/tomb-of-the-mask/' },
{'title':'Tomb Runner','href':'/g/tomb-runner/' },
{'title':'Top Speed Racing 3d','href':'/g/top-speed-racing-3d/' },
{'title':'Toss The Turtle','href':'/g/toss-the-turtle/' },
{'title':'Tower Crash 3d','href':'/g/tower-crash-3d/' },
{'title':'Tower Defense 2d','href':'/g/tower-defense-2d/' },
{'title':'Tower Of Destiny','href':'/g/tower-of-destiny/' },
{'title':'Crazy Traffic Control','href':'/g/crazy-traffic-control/' },
{'title':'Traffic Escape','href':'/g/traffic-escape/' },
{'title':'Traffic Jam 3d','href':'/g/traffic-jam-3d/' },
{'title':'Traffic Mania','href':'/g/traffic-mania/' },
{'title':'Traffic Rider','href':'/g/traffic-rider/' },
{'title':'Traffic Rush','href':'/g/traffic-rush/' },
{'title':'Tribals Io','href':'/g/tribals-io/' },
{'title':'Tricksplit Io','href':'/g/tricksplit-io/' },
{'title':'Truck Traffic','href':'/g/truck-traffic/' },
{'title':'Tube Clicker','href':'/g/tube-clicker/' },
{'title':'Tube Jumpers','href':'/g/tube-jumpers/' },
{'title':'Tunnel Rush','href':'/g/tunnel-rush/' },
{'title':'Tunnel Rush 2','href':'/g/tunnel-rush-2/' },
{'title':'Turn Turn','href':'/g/turn-turn/' },
{'title':'Two Ball 3d','href':'/g/two-ball-3d/' },
{'title':'Two Ball 3d Dark','href':'/g/two-ball-3d-dark/' },
{'title':'Two Neon Boxes','href':'/g/two-neon-boxes/' },
{'title':'Two Tunnel 3d','href':'/g/two-tunnel-3d/' },
{'title':'Unicycle Hero','href':'/g/unicycle-hero/' },
{'title':'Unicycle Legend','href':'/g/unicycle-legend/' },
{'title':'Uno','href':'/g/uno/' },
{'title':'Venge Io','href':'/g/venge-io/' },
{'title':'Vex 3','href':'/g/vex-3/' },
{'title':'Vex 4','href':'/g/vex-4/' },
{'title':'Vex 5','href':'/g/vex-5/' },
{'title':'Vex 6','href':'/g/vex-6/' },
{'title':'Vex 7','href':'/g/vex-7/' },
{'title':'Vex 8','href':'/g/vex-8/' },
{'title':'Volley Random','href':'/g/volley-random/' },
{'title':'Voxiom Io','href':'/g/voxiom-io/' },
{'title':'War Brokers Io','href':'/g/war-brokers-io/' },
{'title':'Water Color Sort','href':'/g/water-color-sort/' },
{'title':'We Become What We Be Hold','href':'/g/we-become-what-we-be-hold/' },
{'title':'Wheelie Bike','href':'/g/wheelie-bike/' },
{'title':'Wheely 2','href':'/g/wheely-2/' },
{'title':'Wheely 3','href':'/g/wheely-3/' },
{'title':'Wheely 5','href':'/g/wheely-5/' },
{'title':'Wizard Mike','href':'/g/wizard-mike/' },
{'title':'Wood Blocks 3d','href':'/g/wood-blocks-3d/' },
{'title':'Word City Crossed','href':'/g/word-city-crossed/' },
{'title':'Word Slide','href':'/g/word-slide/' },
{'title':'Wordle','href':'/g/wordle/' },
{'title':'Wordle Infinite','href':'/g/wordle-infinite/' },
{'title':'Wordle Unlimited','href':'/g/wordle-unlimited/' },
{'title':'Words Search Classic Edition','href':'/g/words-search-classic-edition/' },
{'title':'Worlds Hardest Game 2','href':'/g/worlds-hardest-game-2/' },
{'title':'Wormate Io','href':'/g/wormate-io/' },
{'title':'Wrassling','href':'/g/wrassling/' },
{'title':'Wrestle Bros','href':'/g/wrestle-bros/' },
{'title':'X Trial Racing','href':'/g/x-trial-racing/' },
{'title':'Yohoho Io','href':'/g/yohoho-io/' },
{'title':'Zeepkist Crash 2d','href':'/g/zeepkist-crash-2d/' },
{'title':'Zombie Shooter 2d','href':'/g/zombie-shooter-2d/' },
{'title':'Zombs Royale Io','href':'/g/zombs-royale-io/' },
{'title':'Zuck Vs Musk Techbro Beatdown','href':'/g/zuck-vs-musk-techbro-beatdown/' },
{'title':'2048 Multitask','href':'/g/2048-multitask/' },
{'title':'4x4 Drive Offroad','href':'/g/4x4-drive-offroad/' },
{'title':'Age Of War','href':'/g/age-of-war/' },
{'title':'Alien Hominid','href':'/g/alien-hominid/' },
{'title':'Ape Sling','href':'/g/ape-sling/' },
{'title':'Aqua Thrills','href':'/g/aqua-thrills/' },
{'title':'Arena Noob Vs Pro','href':'/g/arena-noob-vs-pro/' },
{'title':'Athletics Hero','href':'/g/athletics-hero/' },
{'title':'Awesome Tanks','href':'/g/awesome-tanks/' },
{'title':'B Cubed','href':'/g/b-cubed/' },
{'title':'Bank Robbery 2','href':'/g/bank-robbery-2/' },
{'title':'Big Tall Small','href':'/g/big-tall-small/' },
{'title':'Block Tanks','href':'/g/block-tanks/' },
{'title':'Block The Pig','href':'/g/block-the-pig/' },
{'title':'Blocky Blast Puzzle','href':'/g/blocky-blast-puzzle/' },
{'title':'Bloons Tower Defense 1','href':'/g/bloons-tower-defense-1/' },
{'title':'Boxrob','href':'/g/boxrob/' },
{'title':'Boxrob2','href':'/g/boxrob2/' },
{'title':'Boxrob3','href':'/g/boxrob3/' },
{'title':'Bouncy Basketball','href':'/g/bouncy-basketball/' },
{'title':'Bouncy Dunk','href':'/g/bouncy-dunk/' },
{'title':'Burger Bounty','href':'/g/burger-bounty/' },
{'title':'Burnin Rubber 5 Xs','href':'/g/burnin-rubber-5-xs/' },
{'title':'Burnout Drift Hilltop','href':'/g/burnout-drift-hilltop/' },
{'title':'Burnout Drift Seaport Max','href':'/g/burnout-drift-seaport-max/' },
{'title':'Burrito Bison Launcha Libre','href':'/g/burrito-bison-launcha-libre/' },
{'title':'Bus Parking 3d','href':'/g/bus-parking-3d/' },
{'title':'Candy Jump','href':'/g/candy-jump/' },
{'title':'Cannon Basketball','href':'/g/cannon-basketball/' },
{'title':'Cannon Basketball 2','href':'/g/cannon-basketball-2/' },
{'title':'Cannon Basketball 3','href':'/g/cannon-basketball-3/' },
{'title':'Cannon Strike','href':'/g/cannon-strike/' },
{'title':'Car Climb Racing','href':'/g/car-climb-racing/' },
{'title':'Car Drift Racers 2','href':'/g/car-drift-racers-2/' },
{'title':'Car Simulator Arena','href':'/g/car-simulator-arena/' },
{'title':'Cars Simulator','href':'/g/cars-simulator/' },
{'title':'Cars Thief','href':'/g/cars-thief/' },
{'title':'Cars Thief Tank Edition','href':'/g/cars-thief-tank-edition/' },
{'title':'Cartoon Mini Racing','href':'/g/cartoon-mini-racing/' },
{'title':'Cat Gunner Super Zombie Shoot','href':'/g/cat-gunner-super-zombie-shoot/' },
{'title':'Cat Trap','href':'/g/cat-trap/' },
{'title':'City Bike Stunt 2','href':'/g/city-bike-stunt-2/' },
{'title':'City Car Driving Stunt Master','href':'/g/city-car-driving-stunt-master/' },
{'title':'City Coach Bus Sim','href':'/g/city-coach-bus-sim/' },
{'title':'City Rider','href':'/g/city-rider/' },
{'title':'Cluster Rush','href':'/g/cluster-rush/' },
{'title':'Coffee Shop','href':'/g/coffee-shop/' },
{'title':'Color Road','href':'/g/color-road/' },
{'title':'Color Road 2','href':'/g/color-road-2/' },
{'title':'Color Switch','href':'/g/color-switch/' },
{'title':'Color Tunnel','href':'/g/color-tunnel/' },
{'title':'Color Tunnel 2','href':'/g/color-tunnel-2/' },
{'title':'Crazy Ball 3d','href':'/g/crazy-ball-3d/' },
{'title':'Crowd Run 3d','href':'/g/crowd-run-3d/' },
{'title':'Cubefield','href':'/g/cubefield/' },
{'title':'Cubes King','href':'/g/cubes-king/' },
{'title':'Cubito','href':'/g/cubito/' },
{'title':'Cubito Mayhem','href':'/g/cubito-mayhem/' },
{'title':'Curve Ball 3d','href':'/g/curve-ball-3d/' },
{'title':'Cut The Rope Holiday','href':'/g/cut-the-rope-holiday/' },
{'title':'Cut The Rope Time Travel','href':'/g/cut-the-rope-time-travel/' },
{'title':'Cyber Cars Punk Racing','href':'/g/cyber-cars-punk-racing/' },
{'title':'Dark Runner','href':'/g/dark-runner/' },
{'title':'Death Chase','href':'/g/death-chase/' },
{'title':'Death Chase 3','href':'/g/death-chase-3/' },
{'title':'Deepest Sword','href':'/g/deepest-sword/' },
{'title':'Deer Simulator','href':'/g/deer-simulator/' },
{'title':'Demolition Derby Crash Racing','href':'/g/demolition-derby-crash-racing/' },
{'title':'Desert Car Racing 1','href':'/g/desert-car-racing-1/' },
{'title':'Detective Loupe Puzzle','href':'/g/detective-loupe-puzzle/' },
{'title':'Dino Chrome Io','href':'/g/dino-chrome-io/' },
{'title':'Dog Simulator 3d','href':'/g/dog-simulator-3d/' },
{'title':'Doll Designer','href':'/g/doll-designer/' },
{'title':'Doodle Champion Island','href':'/g/doodle-champion-island/' },
{'title':'Doom 2','href':'/g/doom-2/' },
{'title':'Dragon World','href':'/g/dragon-world/' },
{'title':'Draw The Hill','href':'/g/draw-the-hill/' },
{'title':'Drift Dudes','href':'/g/drift-dudes/' },
{'title':'Drop Kick World Cup 2018','href':'/g/drop-kick-world-cup-2018/' },
{'title':'Drunken Duel','href':'/g/drunken-duel/' },
{'title':'Dune Game','href':'/g/dune-game/' },
{'title':'Dunkbrush','href':'/g/dunkbrush/' },
{'title':'Dunker','href':'/g/dunker/' },
{'title':'E Scooter','href':'/g/e-scooter/' },
{'title':'Eagle Ride','href':'/g/eagle-ride/' },
{'title':'Eagler Craft','href':'/g/eagler-craft/' },
{'title':'Earn To Die','href':'/g/earn-to-die/' },
{'title':'Eliza Mall Mania','href':'/g/eliza-mall-mania/' },
{'title':'Endless Truck','href':'/g/endless-truck/' },
{'title':'Energy','href':'/g/energy/' },
{'title':'Eparkour Io','href':'/g/eparkour-io/' },
{'title':'Epic Basketball','href':'/g/epic-basketball/' },
{'title':'Escaping The Prison','href':'/g/escaping-the-prison/' },
{'title':'Eugenes Life','href':'/g/eugenes-life/' },
{'title':'Evo City Driving','href':'/g/evo-city-driving/' },
{'title':'Extreme Car Driving Simulator','href':'/g/extreme-car-driving-simulator/' },
{'title':'Extreme Car Parking','href':'/g/extreme-car-parking/' },
{'title':'Extreme Off Road Cars','href':'/g/extreme-off-road-cars/' },
{'title':'Extreme Off Road Cars 3 Cargo','href':'/g/extreme-off-road-cars-3-cargo/' },
{'title':'Extreme Pamplona','href':'/g/extreme-pamplona/' },
{'title':'Extremeoffroadcars2','href':'/g/extremeoffroadcars2/' },
{'title':'Factory Balls Forever','href':'/g/factory-balls-forever/' },
{'title':'Fairy Dressup','href':'/g/fairy-dressup/' },
{'title':'Fall Guys Ultimate Knockout','href':'/g/fall-guys-ultimate-knockout/' },
{'title':'Falling Fred','href':'/g/falling-fred/' },
{'title':'Fancy Pants','href':'/g/fancy-pants/' },
{'title':'Fancy Pants 2','href':'/g/fancy-pants-2/' },
{'title':'Fancy Pants 3','href':'/g/fancy-pants-3/' },
{'title':'Fleeing The Complex','href':'/g/fleeing-the-complex/' },
{'title':'Flip Bottle','href':'/g/flip-bottle/' },
{'title':'Flipper Dunk 3d','href':'/g/flipper-dunk-3d/' },
{'title':'Flying Car Simulator','href':'/g/flying-car-simulator/' },
{'title':'Fnafsl','href':'/g/fnafsl/' },
{'title':'Foot Chinko','href':'/g/foot-chinko/' },
{'title':'Football Bros','href':'/g/football-bros/' },
{'title':'Forged Alliance Forever','href':'/g/forged-alliance-forever/' },
{'title':'Fortnite','href':'/g/fortnite/' },
{'title':'Fortride Open World','href':'/g/fortride-open-world/' },
{'title':'Fortz','href':'/g/fortz/' },
{'title':'Fred Running','href':'/g/fred-running/' },
{'title':'Free The Key','href':'/g/free-the-key/' },
{'title':'Friday Night Funkin','href':'/g/friday-night-funkin/' },
{'title':'Funny Shooter Destroy All','href':'/g/funny-shooter-destroy-all/' },
{'title':'Furious Racing 3d','href':'/g/furious-racing-3d/' },
{'title':'Gacha Life','href':'/g/gacha-life/' },
{'title':'Galaga','href':'/g/galaga/' },
{'title':'Gartic Phone Io','href':'/g/gartic-phone-io/' },
{'title':'Gladihoppers','href':'/g/gladihoppers/' },
{'title':'Go Kart Go Ultra','href':'/g/go-kart-go-ultra/' },
{'title':'Gobble','href':'/g/gobble/' },
{'title':'Google Feud','href':'/g/google-feud/' },
{'title':'Google Snake','href':'/g/google-snake/' },
{'title':'Gp Moto Racing','href':'/g/gp-moto-racing/' },
{'title':'Gp Moto Racing 3','href':'/g/gp-moto-racing-3/' },
{'title':'Grapple Grip','href':'/g/grapple-grip/' },
{'title':'Grindcraft','href':'/g/grindcraft/' },
{'title':'Growden Io','href':'/g/growden-io/' },
{'title':'Guess The Kitty','href':'/g/guess-the-kitty/' },
{'title':'Gun Blood','href':'/g/gun-blood/' },
{'title':'Gun Fest','href':'/g/gun-fest/' },
{'title':'Halloween Lonely Road Racing','href':'/g/halloween-lonely-road-racing/' },
{'title':'Halloween Skeleton Smash','href':'/g/halloween-skeleton-smash/' },
{'title':'Happy Room','href':'/g/happy-room/' },
{'title':'Head Basketball','href':'/g/head-basketball/' },
{'title':'Heart Star','href':'/g/heart-star/' },
{'title':'Hexbee Merger','href':'/g/hexbee-merger/' },
{'title':'Hextris','href':'/g/hextris/' },
{'title':'Hide And Smash','href':'/g/hide-and-smash/' },
{'title':'Highway Bike Simulator','href':'/g/highway-bike-simulator/' },
{'title':'Highway Racer','href':'/g/highway-racer/' },
{'title':'Highway Rider Extreme','href':'/g/highway-rider-extreme/' },
{'title':'Highway Traffic','href':'/g/highway-traffic/' },
{'title':'Hill Climb Racing','href':'/g/hill-climb-racing/' },
{'title':'Hills Of Steel','href':'/g/hills-of-steel/' },
{'title':'Horse Shoeing','href':'/g/horse-shoeing/' },
{'title':'Horse Simulator 3d','href':'/g/horse-simulator-3d/' },
{'title':'Hover Racer','href':'/g/hover-racer/' },
{'title':'Icy Purple Head 3','href':'/g/icy-purple-head-3/' },
{'title':'Icy Purple Head Superslide','href':'/g/icy-purple-head-superslide/' },
{'title':'Icycle','href':'/g/icycle/' },
{'title':'Idle Ants','href':'/g/idle-ants/' },
{'title':'Idle Dice','href':'/g/idle-dice/' },
{'title':'Idle Digging Tycoon','href':'/g/idle-digging-tycoon/' },
{'title':'Idle Lumber Inc','href':'/g/idle-lumber-inc/' },
{'title':'Idle Miner','href':'/g/idle-miner/' },
{'title':'Idle Restaurants','href':'/g/idle-restaurants/' },
{'title':'Idle Startup Tycoon','href':'/g/idle-startup-tycoon/' },
{'title':'Impossible Tic Tac Toe','href':'/g/impossible-tic-tac-toe/' },
{'title':'Indian Truck','href':'/g/indian-truck/' },
{'title':'Indian Uphill Bus Simulator 3d','href':'/g/indian-uphill-bus-simulator-3d/' },
{'title':'Infiltrating The Airship','href':'/g/infiltrating-the-airship/' },
{'title':'Infinity Loop','href':'/g/infinity-loop/' },
{'title':'Interactive Buddy','href':'/g/interactive-buddy/' },
{'title':'Iron Snout 2','href':'/g/iron-snout-2/' },
{'title':'Jet Boy','href':'/g/jet-boy/' },
{'title':'Jewel Shuffle','href':'/g/jewel-shuffle/' },
{'title':'Johnny Revenge','href':'/g/johnny-revenge/' },
{'title':'Jump Up 3d','href':'/g/jump-up-3d/' },
{'title':'Jump Up 3d Mini Basketball','href':'/g/jump-up-3d-mini-basketball/' },
{'title':'Jumping Shell','href':'/g/jumping-shell/' },
{'title':'Kart Wars','href':'/g/kart-wars/' },
{'title':'Kix Dream Soccer','href':'/g/kix-dream-soccer/' },
{'title':'Life Choices Life Simulator','href':'/g/life-choices-life-simulator/' },
{'title':'Life The Game','href':'/g/life-the-game/' },
{'title':'Linebacker Alley 2','href':'/g/linebacker-alley-2/' },
{'title':'Lines To Fill','href':'/g/lines-to-fill/' },
{'title':'Love Tester','href':'/g/love-tester/' },
{'title':'Ludo Hero','href':'/g/ludo-hero/' },
{'title':'Magikmon','href':'/g/magikmon/' },
{'title':'Make Up Runner','href':'/g/make-up-runner/' },
{'title':'Mega Ramp Car Stunts','href':'/g/mega-ramp-car-stunts/' },
{'title':'Merge Alphabet','href':'/g/merge-alphabet/' },
{'title':'Merge Rainbow','href':'/g/merge-rainbow/' },
{'title':'Microwars','href':'/g/microwars/' },
{'title':'Monster Truck Destroyer','href':'/g/monster-truck-destroyer/' },
{'title':'Moto Road Rash 3d','href':'/g/moto-road-rash-3d/' },
{'title':'Moto X3m 3 Pool Party','href':'/g/moto-x3m-3-pool-party/' },
{'title':'Moto X3m Spooky Land','href':'/g/moto-x3m-spooky-land/' },
{'title':'Murder','href':'/g/murder/' },
{'title':'N Gon','href':'/g/n-gon/' },
{'title':'Nail Stack','href':'/g/nail-stack/' },
{'title':'Neon Biker','href':'/g/neon-biker/' },
{'title':'Neon Racer','href':'/g/neon-racer/' },
{'title':'Noob Basketball Clicker','href':'/g/noob-basketball-clicker/' },
{'title':'Noob Drive','href':'/g/noob-drive/' },
{'title':'Noob Steve','href':'/g/noob-steve/' },
{'title':'Nugget Clicker','href':'/g/nugget-clicker/' },
{'title':'Offroad Forest Racing','href':'/g/offroad-forest-racing/' },
{'title':'Offroad Ultimate','href':'/g/offroad-ultimate/' },
{'title':'Offroader V5','href':'/g/offroader-v5/' },
{'title':'Onion Boy','href':'/g/onion-boy/' },
{'title':'Ooze Odyssey','href':'/g/ooze-odyssey/' },
{'title':'Pacman Remake','href':'/g/pacman-remake/' },
{'title':'Penalty Kick','href':'/g/penalty-kick/' },
{'title':'Pixel Shooter','href':'/g/pixel-shooter/' },
{'title':'Pixwars 2','href':'/g/pixwars-2/' },
{'title':'Plactions','href':'/g/plactions/' },
{'title':'Pokemon Emerald','href':'/g/pokemon-emerald/' },
{'title':'Poly Track','href':'/g/poly-track/' },
{'title':'Poppy Glamrock','href':'/g/poppy-glamrock/' },
{'title':'Power Badminton','href':'/g/power-badminton/' },
{'title':'Ragdoll Archers','href':'/g/ragdoll-archers/' },
{'title':'Real Garbage Truck','href':'/g/real-garbage-truck/' },
{'title':'Rogue Dunk','href':'/g/rogue-dunk/' },
{'title':'Run 3','href':'/g/run-3/' },
{'title':'Shady Bears','href':'/g/shady-bears/' },
{'title':'Shootz','href':'/g/shootz/' },
{'title':'Slow Roads','href':'/g/slow-roads/' },
{'title':'Squid Game','href':'/g/squid-game/' },
{'title':'Steal A Brainrot','href':'/g/steal-a-brainrot/' },
{'title':'Stick Merge Halloween','href':'/g/stick-merge-halloween/' },
{'title':'Stickman Fighter 2','href':'/g/stickman-fighter-2/' },
{'title':'Stickman Fighter Epic Battle','href':'/g/stickman-fighter-epic-battle/' },
{'title':'Stickman Fighter Epic Battle 2','href':'/g/stickman-fighter-epic-battle-2/' },
{'title':'Stickman Run','href':'/g/stickman-run/' },
{'title':'Stickman School Run','href':'/g/stickman-school-run/' },
{'title':'Street Ball Star','href':'/g/street-ball-star/' },
{'title':'Striker Dummies','href':'/g/striker-dummies/' },
{'title':'Stunt Biker 3d','href':'/g/stunt-biker-3d/' },
{'title':'Stunt Car Challenge 3','href':'/g/stunt-car-challenge-3/' },
{'title':'Stupid Zombies','href':'/g/stupid-zombies/' },
{'title':'Subway Runner','href':'/g/subway-runner/' },
{'title':'Subway Surfers Beijing','href':'/g/subway-surfers-beijing/' },
{'title':'Subway Surfers Havana','href':'/g/subway-surfers-havana/' },
{'title':'Subway Surfers Hongkong','href':'/g/subway-surfers-hongkong/' },
{'title':'Subway Surfers Houston','href':'/g/subway-surfers-houston/' },
{'title':'Subway Surfers Monaco','href':'/g/subway-surfers-monaco/' },
{'title':'Subway Surfers Mumbai','href':'/g/subway-surfers-mumbai/' },
{'title':'Subway Surfers New Orleans','href':'/g/subway-surfers-new-orleans/' },
{'title':'Subway Surfers Singapore','href':'/g/subway-surfers-singapore/' },
{'title':'Subway Surfers Tokyo','href':'/g/subway-surfers-tokyo/' },
{'title':'Subway Surfers Venice','href':'/g/subway-surfers-venice/' },
{'title':'Subway Surfers Winter Holiday','href':'/g/subway-surfers-winter-holiday/' },
{'title':'Swatforce Vs Terrorists','href':'/g/swatforce-vs-terrorists/' },
{'title':'Swingo','href':'/g/swingo/' },
{'title':'Swipe Fighter Heroes','href':'/g/swipe-fighter-heroes/' },
{'title':'Tag','href':'/g/tag/' },
{'title':'Tap Goal','href':'/g/tap-goal/' },
{'title':'Temple Of Boom','href':'/g/temple-of-boom/' },
{'title':'Temple Run','href':'/g/temple-run/' },
{'title':'Temple Run 2 Frozen Shadows','href':'/g/temple-run-2-frozen-shadows/' },
{'title':'Temple Run 2 Holi Festival','href':'/g/temple-run-2-holi-festival/' },
{'title':'Temple Run 2 Jungle Fall','href':'/g/temple-run-2-jungle-fall/' },
{'title':'The Backrooms 3d','href':'/g/the-backrooms-3d/' },
{'title':'The Speed Ninja','href':'/g/the-speed-ninja/' },
{'title':'Thumb Fighter Christmas','href':'/g/thumb-fighter-christmas/' },
{'title':'Time Clones','href':'/g/time-clones/' },
{'title':'Time Shooter 3 Swat','href':'/g/time-shooter-3-swat/' },
{'title':'Tiny Cars','href':'/g/tiny-cars/' },
{'title':'Tomb Of The Mask Color','href':'/g/tomb-of-the-mask-color/' },
{'title':'Toon Off','href':'/g/toon-off/' },
{'title':'Top Speed 3d','href':'/g/top-speed-3d/' },
{'title':'Traffic Control','href':'/g/traffic-control/' },
{'title':'Traffic Run','href':'/g/traffic-run/' },
{'title':'Traffic Tom','href':'/g/traffic-tom/' },
{'title':'Tricks','href':'/g/tricks/' },
{'title':'Truck Trials','href':'/g/truck-trials/' },
{'title':'Turbo Moto Racer','href':'/g/turbo-moto-racer/' },
{'title':'Ultimate Car Arena','href':'/g/ultimate-car-arena/' },
{'title':'Ultimate Car Driving','href':'/g/ultimate-car-driving/' },
{'title':'Ultimate Off Road Cars','href':'/g/ultimate-off-road-cars/' },
{'title':'Ultimate Offroad Cars 2','href':'/g/ultimate-offroad-cars-2/' },
{'title':'Volleyball Challenge','href':'/g/volleyball-challenge/' },
{'title':'War Of Sticks','href':'/g/war-of-sticks/' },
{'title':'Where Is My Cat','href':'/g/where-is-my-cat/' },
{'title':'Who Is','href':'/g/who-is/' },
{'title':'Wheely 4','href':'/g/wheely-4/' },
{'title':'Wheely 6','href':'/g/wheely-6/' },
{'title':'Wheely 7','href':'/g/wheely-7/' },
{'title':'Wheely 8','href':'/g/wheely-8/' },
{'title':'Word City Uncrossed','href':'/g/word-city-uncrossed/' },
{'title':'Wordle Plus','href':'/g/wordle-plus/' },
{'title':'Zombie Derby Pixel Survival','href':'/g/zombie-derby-pixel-survival/' },
{'title':'Zombocalypse Shooter','href':'/g/zombocalypse-shooter/' },
    ].map((item) => {
        const imageName = item.href.replace(/^\/g\//, '').replace(/\/$/, '');
        return {
            ...item,
            titleLower: item.title.toLowerCase(),
            img: `/assest/images/${imageName}.webp`
        };
    });

    const topGames = games.slice(0, 35);

    const createElement = (tag, className, text) => {
        const el = document.createElement(tag);
        if (className) el.className = className;
        if (text !== undefined) el.textContent = text;
        return el;
    };

    const hideDropdown = () => {
        searchSuggestions.classList.add('hidden');
        searchSuggestions.innerHTML = '';
    };

    const renderDropdown = (query) => {
        const searchValue = query.trim().toLowerCase();
        const matches = searchValue ? games.filter((game) => game.titleLower.includes(searchValue)) : [];
        const items = matches.slice(0, 4);
        searchSuggestions.innerHTML = '';

        if (!searchValue) {
            hideDropdown();
            return;
        }

        if (!items.length) {
            const empty = createElement('div', 'search-dropdown-empty');
            const message = createElement('div', null, `No games found for “${query}”.`);
            const seeAllButton = createElement('button', 'search-dropdown-see-all', 'Show top games');
            seeAllButton.type = 'button';
            seeAllButton.addEventListener('click', () => submitSearch(query));
            empty.appendChild(message);
            empty.appendChild(seeAllButton);
            searchSuggestions.appendChild(empty);
            searchSuggestions.classList.remove('hidden');
            return;
        }

        items.forEach((game) => {
            const item = createElement('div', 'search-dropdown-item');
            const thumb = createElement('img', 'search-dropdown-thumb');
            thumb.src = game.img;
            thumb.alt = game.title;
            thumb.loading = 'lazy';
            const title = createElement('span', null, game.title);
            item.appendChild(thumb);
            item.appendChild(title);
            item.addEventListener('click', () => {
                window.location.href = game.href;
            });
            searchSuggestions.appendChild(item);
        });

        const seeAll = createElement('div', 'search-dropdown-see-all', `See all results for “${query}”`);
        seeAll.addEventListener('click', () => submitSearch(query));
        searchSuggestions.appendChild(seeAll);
        searchSuggestions.classList.remove('hidden');
    };

    const renderResults = (query) => {
        const searchValue = query.trim().toLowerCase();
        const matches = searchValue ? games.filter((game) => game.titleLower.includes(searchValue)) : [];
        const showGames = matches.length ? matches : topGames;

        resultsTitle.textContent = searchValue
            ? matches.length
                ? `Results for “${query}”`
                : `No results for “${query}”`
            : 'Top games';

        resultsNote.textContent = searchValue
            ? matches.length
                ? `Showing ${showGames.length} games that match your search.`
                : 'No direct matches were found, so we are showing our top 35 games instead.'
            : 'Browse our top 35 games.';

        resultsGrid.innerHTML = '';

        showGames.forEach((game) => {
            const card = createElement('a', 'search-result-card');
            card.href = game.href;
            const thumb = createElement('img', 'search-result-card-thumb');
            thumb.src = game.img;
            thumb.alt = game.title;
            const body = createElement('div', 'search-result-card-body', game.title);
            card.appendChild(thumb);
            card.appendChild(body);
            resultsGrid.appendChild(card);
        });
    };

    const hideSearchResults = () => {
        searchResultsPage.classList.remove('active');
        searchInput.value = '';
    };

    const submitSearch = (query) => {
        const trimmed = query.trim();
        if (!trimmed) {
            hideDropdown();
            hideSearchResults();
            return;
        }
        renderResults(trimmed);
        searchResultsPage.classList.add('active');
        hideDropdown();
    };

    resultsClose.addEventListener('click', hideSearchResults);

    const openMobileSearch = () => {
        if (!mobileSearchPopup || !mobileSearchInput) return;
        mobileSearchPopup.classList.add('active');
        mobileSearchPopup.setAttribute('aria-hidden', 'false');
        mobileSearchInput.focus();
    };

    const closeMobileSearch = (options = { hideResults: true }) => {
        if (!mobileSearchPopup || !mobileSearchInput) return;
        mobileSearchPopup.classList.remove('active');
        mobileSearchPopup.setAttribute('aria-hidden', 'true');
        mobileSearchInput.value = '';
        if (options.hideResults) {
            hideSearchResults();
        }
    };

    if (mobileSearchButton) {
        mobileSearchButton.addEventListener('click', openMobileSearch);
    }

    if (mobileSearchClose) {
        mobileSearchClose.addEventListener('click', () => closeMobileSearch({ hideResults: true }));
    }

    if (mobileSearchPopup) {
        mobileSearchPopup.addEventListener('click', (event) => {
            if (event.target === mobileSearchPopup) {
                closeMobileSearch();
            }
        });
    }

    if (mobileSearchInput) {
        mobileSearchInput.addEventListener('keydown', (event) => {
            if (event.key === 'Enter') {
                event.preventDefault();
                submitSearch(mobileSearchInput.value);
                closeMobileSearch({ hideResults: false });
            }
            if (event.key === 'Escape') {
                closeMobileSearch();
            }
        });
    }

    if (mobileSearchForm) {
        mobileSearchForm.addEventListener('submit', (event) => {
            event.preventDefault();
            submitSearch(mobileSearchInput ? mobileSearchInput.value : '');
            closeMobileSearch({ hideResults: false });
        });
    }

    searchInput.addEventListener('input', (event) => {
        renderDropdown(event.target.value || '');
    });

    searchInput.addEventListener('keydown', (event) => {
        if (event.key === 'Enter') {
            event.preventDefault();
            submitSearch(searchInput.value);
        }
        if (event.key === 'Escape') {
            hideDropdown();
            hideSearchResults();
        }
    });

    searchForm.addEventListener('submit', (event) => {
        event.preventDefault();
        submitSearch(searchInput.value);
    });

    document.addEventListener('click', (event) => {
        if (!searchForm.contains(event.target) && !searchSuggestions.contains(event.target)) {
            hideDropdown();
        }
    });
})();